### ISSUE TITLE
Fix linting issues caused due to Function returning constants

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#100]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to fix linting issues caused by functions that are returning constants and are being used in the codebase. A possible fix for this will be to pass the constant as parameters where the function is being used.

Steps to identify the lines to fix:

- Comment or remove or turn the following line to false 

```
 FunctionOnlyReturningConstant:
        active: false

```

- Run `./gradlew detekt` in your terminal 
- You would be able to see which all lines to fix. 

### Contribution

I would love to work on this and more than willing to help anyone who wants to fix this issue 😄 .

**Comment by andrewtavis** [comment]
Closed by #175 🚀 Looking forward to the next one, @DeKaN!
