### ISSUE TITLE
Fix linting issues caused due to too many functions

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#107]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The TooManyFunctions rule in Detekt is currently disabled. This rule helps identify classes that contain too many functions, which can lead to reduced readability and maintainability. The goal is to re-enable this rule to ensure that classes remain manageable and adhere to best practices.

Steps to see which files have to be modified:

- Comment or set to true the following line
```
TooManyFunctions:
    active: true

```
- Run the command `./gradlew detekt`.
- Review the output to see which files and classes need modification.

### Contribution

I would love to take on this issue and am more than happy to helpful anyone fix this issue :)

**Comment by growabeard** [comment]
👋

**Comment by andrewtavis** [comment]
Thanks for picking this up, @growabeard!

**Comment by andrewtavis** [comment]
I'd say we're good to close this as I agree with @growabeard that `SimpleKeyboardIME` and `MyKeyboardView` are not going to be split up anytime soon :) Thanks for all the hard work here, @growabeard!
