### ISSUE TITLE
Fix linting issues caused due to Nested Block Depth 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#108]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The NestedBlockDepth rule is currently disabled. This rule helps in detecting code with excessive nesting, which can make the code harder to read and understand. Re-enabling this rule will help in maintaining clean and readable code.

Steps to see which all lines have to be modified:

- Comment or set to true the following line in detekt.yml:
```
NestedBlockDepth:
    active: true
````
- Run the command ./gradlew detekt.
- Check the output to identify files and lines that need refactoring.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix the issue :)

**Comment by angrezichatterbox** [comment]
I would be working on this :)

**Comment by andrewtavis** [comment]
Thanks for picking this up, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Closed by #259 🚀 Thanks so much, @angrezichatterbox! I'll check in in a few more issues to get your opinions. So much progress when it comes to linting/detekt 🙌
