### ISSUE TITLE
Fix linting issues caused due to Complex conditions 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#109]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The ComplexCondition rule is currently turned off. This rule helps in identifying conditions that are overly complex, which can make the code difficult to understand. Re-enabling this rule will improve code clarity.

Steps to find the lines to modify:

- Comment or set to true the following line in detekt.yml:
```
ComplexCondition:
    active: true

```
- Run the command ./gradlew detekt.
- Review the output to find the complex conditions that need simplification.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix the issue :)

**Comment by albendz** [comment]
Hello - could I try working on this issue?

**Comment by andrewtavis** [comment]
By all means, @albendz! Great to have you in the community :) Please let us know if there's something we can do to help 😊

**Comment by andrewtavis** [comment]
Closed by #201 :) Thanks so much, @albendz! 🚀
