### ISSUE TITLE
Fix linting issue due to Long Parameter List 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#110]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The LongParameterList rule is currently not active. This rule helps in identifying functions with too many parameters, which can make the code less readable and maintainable. Re-enabling this rule will encourage better function design.

Steps to find lines or files to modify:

- Comment or set to true the following line in detekt.yml:
```
LongParameterList:
    active: true

```
- Run the command ./gradlew detekt.
- Examine the results to see which functions need refactoring.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue :)

**Comment by Linfye** [comment]
@andrewtavis This issue can be close by #230 😊

**Comment by andrewtavis** [comment]
Forgot to close it :) Thanks for the reminder and for the PR, @Linfye!
