### ISSUE TITLE
Fix linting issue due to Long Methods

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#111]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The LongMethod rule is currently inactive. This rule identifies methods that are too long, which can affect readability and maintainability. Re-enabling this rule will help in managing method size and improving code quality.

Steps to see which lines have to be modified:

- Comment or set to true the following line in detekt.yml:
```
LongMethod:
    active: true

```
- Execute the command ./gradlew detekt.
- Check the output to find methods that need to be refactored.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue :)

**Comment by henrikth93** [comment]
I can take a look at this one

**Comment by andrewtavis** [comment]
Thanks for picking it up, @henrikth93 :)

**Comment by andrewtavis** [comment]
Closed by #202 :) Thank you, @henrikth93!
