### ISSUE TITLE
Fix linting issues caused due to Cyclomatic Complex Method

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#112]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The CyclomaticComplexMethod rule is currently disabled. This rule helps in detecting methods with high cyclomatic complexity, which can make the code harder to test and maintain. Re-enabling this rule will aid in managing method complexity.

Steps to see which all lines have to be modified:

- Comment or set to true the following line in detekt.yml:

```
CyclomaticComplexMethod:
    active: true

```
- Run the command ./gradlew detekt.
- Review the results to identify methods with high complexity that need refactoring.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue :)

**Comment by angrezichatterbox** [comment]
I would be working on this as well

**Comment by andrewtavis** [comment]
Appreciate you working to close out the linting issues, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Closed by #259 😊 Thanks for the concerted efforts to fix all of these linting issues, @angrezichatterbox! So great that the app is at the state that it is :)
