### ISSUE TITLE
Expand keyboard installation instructions on installation screen

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#113]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of writing the `Installation` screen of the application has `ENABLE KEYBOARD` as the title of the button to select the keyboard. The current state is shown below:

<img width="452" alt="Screenshot 2024-09-14 at 19 42 10" src="https://github.com/user-attachments/assets/9c7ff16f-73e4-4e44-9a68-908995fe850a">

We'd like to expand this with more detailed directions for the user as seen on the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=458-1320&t=J8vmgQqaca9JriVj-1) and below:

![Keyboard Installation - Light](https://github.com/user-attachments/assets/9126c11a-5904-4181-971f-f5aa79ea0733)

The strings needed for this are:
- `app.installation.keyboard.keyboard_settings`
- `app.installation.keyboard.text_2` (we don't need `test_1` for Android)
- `app.installation.keyboard.text_3`
- The Android keyboard icon would go here
- `app.installation.keyboard.text_4`

Included in this would also be adding in the settings cog icon on the upper right corner of the option as is done in the privacy policy page and third party likenesses :)

### Contribution

Happy to discuss this with someone and review or also get to it myself eventually 😊

**Comment by andrewtavis** [comment]
@Linfye, I'm thinking that this could be a pretty straightforward issue for you given your work to add in the other pages with the upper right icons? Would you like to work on this one?

**Comment by andrewtavis** [comment]
Looking into #119 at the same time might also make sense, as the functionality of the button will change from enabling a keyboard to selecting keyboards to install, which is handled in #119 :) :)

**Comment by Linfye** [comment]
I’m happy to do this, but I’m a bit busy at the moment. I might only be able to work on Scribe in about two weeks, is that okay?

**Comment by andrewtavis** [comment]
100% ok, @Linfye :) I won't assign you for now so it's not on your to do list, but please let us know when you have more availability!

**Comment by Linfye** [comment]
@andrewtavis I am working on this. You can assign me this now. 😊

**Comment by Linfye** [comment]
I'm not quite clear about three things:

1. Does the "Open Scribe settings" with the underline also function like the "settings" at the bottom of the interface to navigate to "Settings" page?

2. How should I use the "Download data" option? Does it require fetching some data from a server?

3. Is the "Quick tutorial" a button (it looks like a button to me)? If so, what page should it open?

Thanks. I'm not quite clear about three things, and I'd like to ask:

Does the "Open Scribe settings" with the underline also function like the "settings" at the bottom of the interface to navigate to a different page?
How should I use the "download data" option under "language data"? Does it require fetching data from the server?

Is the "quick tutorial" a button? If so, what page does it open?

Thanks. :)

**Comment by andrewtavis** [comment]
Hey @Linfye! Answers to your questions:

2. The button for keyboard installation will open the keyboard installation settings for the device. So once you click the button you will be able to install Scribe keyboards, rather than selecting a Scribe keyboard. Specifically it's doing what the user is forced to do by the alert when the app is first installed - install a Scribe keyboard. In this case it's also not "Open Scribe settings" but rather "Open keyboard settings", which is the value of the first i18n key listed above :) 

2. No need to worry about the data download for this issue!

3. Also no need to worry about the tutorial! Sorry, I should have just done a screenshot of the keyboard installation directions :) 

Let me know if I can help any other way!

**Comment by andrewtavis** [comment]
Note that we also need the header above the white background for this as is the style of other sections in the app, so "Keyboard installation" should be above the new directions as shown in the image.

**Comment by andrewtavis** [comment]
See #199 for the other part of this, @Linfye. As of now the user is forced to install a keyboard on first load of an app. After these two issues the user will not be forced to install a keyboard via #119, will be prompted to install a keyboard via the "Open keyboard directions" description on the installation page via the work for this issue, and the settings tab will also prompt the user to install a keyboard with a button if the user has not, with this button similarly opening the keyboard settings of the device 😊

**Comment by andrewtavis** [comment]
Closed by #140 😊 Thanks for being such a great part of the team, @Linfye!
