### ISSUE TITLE
Convert toggles to match Figma designs

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#114]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to convert the toggles of the application to match those found in the designs. As of now the toggles look like the following:

<img width="443" alt="Screenshot 2024-09-14 at 19 14 40" src="https://github.com/user-attachments/assets/1b62fc32-e585-40c8-978e-d7f1834062c5">

Where ideally the toggles would look like those as found in the designs as shown below:

![Select Keyboard - No Keyboard - Light](https://github.com/user-attachments/assets/25adc1cc-4f17-44a9-9a34-0e4eb65ab6c5)

The toggles themselves can be found on Figma [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-2072&t=u8w7568Wwpzvvg5t-1).

### Contribution

Happy to support with this and review or get to it myself as needed! :) :)

**Comment by angrezichatterbox** [comment]
I will work on this issue.

**Comment by andrewtavis** [comment]
Nice @angrezichatterbox! I've had this one in mind as something that would really get the app looking great 😊

I noticed that the `Install keyboards` button in Settings when you don't have a keyboard installed wasn't styled correctly recently. Maybe it was fixed, but if not do you want to include that in here? :)

**Comment by angrezichatterbox** [comment]
<img width="409" alt="Screenshot 2024-10-07 at 11 58 46 PM" src="https://github.com/user-attachments/assets/e964f1bb-440a-452e-b707-2170b0a35dc0">

Should I make any changes to the Install keyboard button here.

**Comment by andrewtavis** [comment]
I think the colors are off in dark mode? I saw it with white text, but maybe it's fixed. That button looks fine :)

**Comment by angrezichatterbox** [comment]
> I think the colors are off in dark mode. I saw it with white text, but maybe it's fixed. That button looks fine :)

Yes, the colors are off in the dark mode. Along with that, a border has to be added like in the home. I will be doing in the PR for this issue :)

**Comment by andrewtavis** [comment]
Nice, @angrezichatterbox! :)

**Comment by andrewtavis** [comment]
Closed by #177 🚀 Thanks for the quick and great work, @angrezichatterbox!
