### ISSUE TITLE
Add ability for menu TextItem to have captions and add one for selecting app language

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#115]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now within the menu `TextItem` doesn't have an allowable `description` field, which is needed to add captions so that elements within the application are consistent. Specifically we'd like `Change which language the Scribe app is in.` via `app.settings.menu.app_language_description` to be added to the `App language` option in `SettingsFragment.kt` as shown in the designs below:

![Select Keyboard - Light](https://github.com/user-attachments/assets/f0638583-6c2c-4221-a48f-09352a6d5e3a)

This issue would add the option to include a `description` field in `TextItem.kt` and then add the description to the menu option specified above :)

### Contribution

Happy to discuss this and review or potentially get to it myself eventually! 😊

**Comment by angrezichatterbox** [comment]
This issue could be closed right as it has been completed.

**Comment by andrewtavis** [comment]
Very true, @angrezichatterbox :) Thanks for keeping an eye on the issues!
