### ISSUE TITLE
Switch highlight color of tab bar options

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#116]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that's needed for the tab bar for the application is to set the highlight color to the opposite Scribe blue given the coloration. The current versions are shown below:

<img width="386" alt="Screenshot 2024-09-14 at 19 32 51" src="https://github.com/user-attachments/assets/deaf518c-c3f5-4eb9-a562-f6e78755161e">

<img width="382" alt="Screenshot 2024-09-14 at 19 33 54" src="https://github.com/user-attachments/assets/8f694540-5714-4696-be2b-70c07645b7f6">

Each highlight color is the Scribe blue for the given color mode. We need the highlight color for light mode to be the dark mode Scribe blue and the highlight color for light mode to be the light mode Scribe blue 💙

### Contribution

Happy to assist with this and review as needed! This is a great `good first issue` for someone wanting to get into Scribe-Android development 😊

**Comment by has9sayed** [comment]
I'm interested in working on this issue. Can I be assigned to it?

**Comment by andrewtavis** [comment]
Sure thing, @has9sayed! Please let us know if you need any help :)

**Comment by andrewtavis** [comment]
Thanks for the contribution here, @has9sayed! Please let us know if there's another issue that would be of interest 😊

**Comment by has9sayed** [comment]
@andrewtavis I'm glad I could contribute. I'll definitely check out other issues and see where I can help next!

**Comment by andrewtavis** [comment]
Looking forward, @has9sayed! :) :)
