### ISSUE TITLE
Remove left margin from application page headers 

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#117]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One thing that's needed for the application is for the page headers to be aligned with the rest of the page content. As shown below, there's a slight left margin that's applied to the page header, which is further applied to back buttons:

<img width="435" alt="Screenshot 2024-09-14 at 19 37 22" src="https://github.com/user-attachments/assets/63a58294-3895-4042-ab70-26fc5dbecc6e">

Within the following image, the section header `Functionality` further has the margin, as does the back button:

<img width="437" alt="Screenshot 2024-09-14 at 19 39 04" src="https://github.com/user-attachments/assets/c6f08916-0b70-4328-889a-c9c67ca0863b">

This issue would remove this margin from the app page headers and back buttons so they're aligned with the start of the white/black sections.

### Contribution

Happy to support someone with this and review the changes! This is a great `good first issue` for someone wanting to get into Scribe-Android development 😊

**Comment by MostafaMohamed2002** [comment]
i would like to contribute , can you assign this to me

**Comment by andrewtavis** [comment]
Closed by #171 🚀 Thanks so much for the quick work here and also for picking another issue up so quickly, @MostafaMohamed2002! Great to have you in the community :)
