### ISSUE TITLE
Increase app UI menu option margins and section padding

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#118]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would work to improve the spacing of app elements within the application. The current state of the menu looks like the following:

<img width="441" alt="Screenshot 2024-09-14 at 19 46 29" src="https://github.com/user-attachments/assets/73c90cbd-337a-4518-89e5-9c6d0953fa30">

Changes that are needed are:
- We need more of a margin around all of the menu options
- We need more spacing between the `App settings` and `Select installed keyboard` sections

The [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=570-1568&t=u8w7568Wwpzvvg5t-1) can be referenced to see what the ideal spacing should be :)

### Contribution

Happy to support with this and review the changes when they come in 😊 This is a great `good first issue` for someone wanting to get into Scribe-Android development 🚀

**Comment by realjoni17** [comment]
hi i want to contribute to this

**Comment by andrewtavis** [comment]
Let's do the PR for #150 first, @realjoni17, but I'll not assign anyone here for now and we can assign you when the other one's done 😊

**Comment by MostafaMohamed2002** [comment]
hi @andrewtavis,
If @realjoni17  is still occupied with #150, I would be happy to take on this issue 😊

**Comment by andrewtavis** [comment]
Let's give @realjoni17 a moment to say that it's ok for you to take over, but I'd be fine with you working on this, @MostafaMohamed2002 :)

**Comment by realjoni17** [comment]
@MostafaMohamed2002 you can contribute to this

**Comment by andrewtavis** [comment]
Thanks for the willingness to pass it over, @realjoni17! Let us know if there's anything we can do to support, @MostafaMohamed2002 😊

**Comment by andrewtavis** [comment]
Closed by #198 🚀 Thanks for the amazing work here, @MostafaMohamed2002! Looking forward to the next issue you pick up 😊
