### ISSUE TITLE
Remove the requirement to install Scribe keyboards

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#119]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in a dev sync from a while ago, the community decided that we do not want to force the user to install a keyboard when they first enter the app. We'd prefer the steps to be shown to the user as will be done in #113 :) From there we would also need a button to prompt the user to install keyboards within settings as shown [here in the Figma designs](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=653-1846&t=u8w7568Wwpzvvg5t-1) and below:

![Select Keyboard - No Keyboard - Light](https://github.com/user-attachments/assets/705720dd-c8d7-49c3-a877-0ea0a2318c94)

The button above would lead the user to the option to select keyboards to install as would be done in the `Installation screen`.

### Contribution

Happy to support with this and review as needed, or could also get to it myself eventually 😊

**Comment by angrezichatterbox** [comment]
<img width="200" alt="Screenshot 2024-09-30 at 3 36 42 PM" src="https://github.com/user-attachments/assets/2300a742-8405-4bd2-9f54-d2599dd63735">

I think this is somewhat done for the current app in one of the PR but the shape and size are not exactly right.

**Comment by andrewtavis** [comment]
Ah yes! Do you want to do the final styling, @angrezichatterbox? And we can also check that there's no notice to install keyboards if there's none installed yet? Feel free to assign and work on this!

**Comment by angrezichatterbox** [comment]
> Ah yes! Do you want to do the final styling, @angrezichatterbox? And we can also check that there's no notice to install keyboards if there's none installed yet? Feel free to assign and work on this!

I will work on it. It's a quick fix.

**Comment by andrewtavis** [comment]
Closed by #163 🚀 Thanks so much for the attention to detail here including the text on the button on the settings page, @angrezichatterbox!
