### ISSUE TITLE
Keyboard UI coloration fixes

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#121]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would fix a few issues with the keyboard coloration. The current Scribe-Android keyboard is shown below:

<img width="470" alt="Screenshot 2024-09-14 at 20 03 43" src="https://github.com/user-attachments/assets/f7f7087e-e483-44b7-9c61-12bb6ab8f273">

Changes that are needed are:
- We want the shift key, `?123` key, backspace key and return key to be the special key color
    - Ideally the return key would be the current blue when the command bar is present once one of the `Translate`, `Conjugate` or `Plural` options is pressed
- It would be good for the background of the area where the Scribe key and autosuggestions are to be the same color as the rest of the keyboard
- The autosuggestions should not have a distinct background to the rest of the keyboard (i.e. their background should be clear)

### Contribution

Happy to support with this and review when all's ready! Can also get to it myself eventually :) :)

**Comment by angrezichatterbox** [comment]
I will work on this issue.

**Comment by angrezichatterbox** [comment]
> Thanks @angrezichatterbox! Let me know if another call before Hacktoberfest to discuss the project could help. We're getting into a phase where larger issues like implementing commands will start being worked on, and it would likely make sense to plan those out before making them 😊

Yes it would be helpful for a call. As I too would like to know what would be worked on next and how is it being planned.

**Comment by andrewtavis** [comment]
Let me know when would work for you on Element :) I can do Friday after work or the weekend when it's not too late for you 😊

**Comment by angrezichatterbox** [comment]
> * We want the shift key, `?123` key, backspace key and return key to be the special key color

Could I get some idea on what the special key color means. Return key should change color accordingly to state like idle state means it would be the usual dark and white color and for other states we would have scribe blue color. What should be done about the ?123 and backspace.

**Comment by andrewtavis** [comment]
Definitely could have been more clear here :) So if you check Scribe-iOS, `keySpecial.colorset` is the one that I'm talking about for the special key colors, and `keyPressed.colorset` is what we'll use for the shift key being pressed. If any of the colors within `Assets.xcassets/Colors` is missing in Android, then it might make sense to add them in this issue as well 🎨😊

**Comment by andrewtavis** [comment]
Closed by #132 with a quick update of the readme in 8ea6bf3 😊 Great to see all the progress finally on display in the readme, @angrezichatterbox! We're really getting there :)
