### ISSUE TITLE
App keyboard functionality is broken

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#123]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

There are various problems with the current Scribe-Android keyboard, which are likely coming from some of the updates to the build process and code refactoring. Specifically issues include:

- Keys not functioning on first keyboard load
- Delete not deleting if there is text
- Getting a ~`Scribe seems to not be functioning` warning where the user is prompted to wait or restart

### Device type

Emulator is a Pixel 8 Pro

### Versions

Current development branch

**Comment by andrewtavis** [comment]
This would be another great one to look into, @angrezichatterbox! From here with a few more of the keyboard issues done we can start working on the command functionality 🚀

**Comment by angrezichatterbox** [comment]
> This would be another great one to look into, @angrezichatterbox! From here with a few more of the keyboard issues done we can start working on the command functionality 🚀

I will look into this issue and try figuring out why the keyboard is crashing.  I will work on #120 after this.

**Comment by andrewtavis** [comment]
Sounds perfect, @angrezichatterbox! :)

**Comment by angrezichatterbox** [comment]
I have created a pull request for this issue.

**Comment by andrewtavis** [comment]
Thanks for the fixes here, @angrezichatterbox! Really nice to have the keyboard working again :) :) The issues I was facing were Android Studio based, btw. I just reinstalled it as it seemed that some of the settings were getting crossed up.

Let me know if #121 sounds good as a next issue! Open to suggestions of course, but that one should definitely be a priority :)

**Comment by angrezichatterbox** [comment]
> Thanks for the fixes here, @angrezichatterbox! Really nice to have the keyboard working again :) :) The issues I was facing were Android Studio based, btw. I just reinstalled it as it seemed that some of the settings were getting crossed up.
> 
> Let me know if #121 sounds good as a next issue! Open to suggestions of course, but that one should definitely be a priority :)

Yes #121 sounds good as it would fix the visual of the keyboard to some extent before Hacktoberfest.
