### ISSUE TITLE
Fix linting issues due to Large Classes 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#125]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The LargeClass rule is currently disabled. This rule helps in detecting classes that are too large, which can lead to code that is harder to maintain. Re-enabling this rule will aid in managing class complexity.

Steps to see which lines have to be modified:

1. Comment or set to true the following line in detekt.yml:

```
LargeClass:
    active: true

```

2. Run the command `./gradlew detekt`.
3. Review the results to identify classes that need refactoring.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue. :)

**Comment by andrewtavis** [comment]
Closed by #185 :) Thanks, @KesharwaniArpita!
