### ISSUE TITLE
Fix linting issues due to Empty Catch Block 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#127]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The `EmptyCatchBlock` rule is currently disabled. This rule helps detect empty catch blocks, which can lead to unnoticed errors. Re-enabling this rule will help ensure proper error handling.

**Steps to see which lines have to be modified:**
1. Comment or set to true the following line in `detekt.yml`:
   ```yaml
   empty-blocks:
       EmptyCatchBlock:
           active: true
   ```
2. Run the command `./gradlew detekt`.
3. Review the results to identify any empty catch blocks that need addressing.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue. :)

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis , Can you assign me this issue?

**Comment by angrezichatterbox** [comment]
You have been assigned the issue :)  Thanks for taking up the issue
