### ISSUE TITLE
Fix linting issue due to InvalidPackageDeclaration

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#128]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The `InvalidPackageDeclaration` rule is currently disabled. This rule helps ensure that package declarations are valid, promoting a better project structure. Re-enabling this rule will assist in maintaining proper package organization.

**Steps to see which lines have to be modified:**
1. Comment or set to true the following line in `detekt.yml`:
   ```yaml
   naming:
       InvalidPackageDeclaration:
           active: true
   ```
2. Run the command `./gradlew detekt`.
3. Review the results to identify any invalid package declarations that need fixing.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue. :)

**Comment by andrewtavis** [comment]
Closed by #175 😊 Thanks for getting all these done, @DeKaN!
