### ISSUE TITLE
Fix linting issues due to ImplicitDefaultLocale

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#130]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The `ImplicitDefaultLocale` rule is currently disabled. This rule helps detect potential bugs related to the use of the default locale in the code. Re-enabling this rule will help ensure that locale-specific operations are handled correctly.

**Steps to see which lines have to be modified:**
1. Comment or set to true the following line in `detekt.yml`:
   ```yaml
   potential-bugs:
       ImplicitDefaultLocale:
           active: true
   ```
2. Run the command `./gradlew detekt`.
3. Review the results to identify any potential issues related to default locale usage.

### Contribution

I would love to work on this issue and am more than willing to help anyone fix this issue. :)

**Comment by andrewtavis** [comment]
Closed by #183 :) Great to have all of the support from you here, @DeKaN 😊
