### ISSUE TITLE
Load in new version of Scribe data with lexeme based IDs

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#134]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

All languages

### Description

- Note that this issue is blocked by https://github.com/scribe-org/Scribe-Data/issues/142

Once [Scribe-Data#142](https://github.com/scribe-org/Scribe-Data/issues/142) is finished, we need to load the new version of the data into Scribe-Android to allow for development of the features based on the lexeme ID based data. As of now the Scribe data is based on each string being its own identifier, but we want to switch it to there being a Wikidata lexeme ID for each row where some lemmas for the lexemes could be the same.

**Comment by andrewtavis** [comment]
Note @angrezichatterbox: This issue is going to block most of the keyboard issues, and likely won't be finished for at least another few weeks. I'm realizing that the data that we have now is not the version of the data that we want in Scribe-Android, as we made the decision to update the data indexing as described above. It makes sense to get the new version of the data done before we start implementing features and then need to rework them later.

Hope this makes sense! 😊

**Comment by MahmoudMabrok** [comment]
is there a new updates here @andrewtavis

**Comment by andrewtavis** [comment]
I'm waiting on one final PR from Scribe-Data to be completed and then will finish my current issue there and bring the data in :) Should be done by this weekend 😊

**Comment by andrewtavis** [comment]
Closed by c83a18b :) CC @angrezichatterbox that we're all done here :) Sorry for the wait!
