### ISSUE TITLE
[Annotation] Style first autosuggestion button based on the gender of a word typed

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#135]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is the first to start adding in Scribe command functionality to Scribe-Android 🚀 

When a user types a word that is found in a nouns table we'd like the first autosuggestion button to change based on the gender of the word. The suggestion key should also be disabled when an annotation is being shown.

The changes are the following:

- For feminine the key is red with an F
- For masculine the key is blue with an M
- For neutral the key is green with an N
- For common (combination of feminine and masculine in Swedish) the key is purple with a C
- For plural the key is orange with a PL

The letters described above should also change based on the language. See [Scribe-iOS/Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift#L37](https://github.com/scribe-org/Scribe-iOS/blob/ba8da43a5d3f791a9567cb8c6ff6496c85350987/Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift#L37) for the needed conversions for Swedish and Russian.

- Note that this issue is blocked by #134, which is blocked by https://github.com/scribe-org/Scribe-Data/issues/142

### Contribution

Happy to support with this and get to it myself eventually if need be! This is the first Scribe functionality within Scribe-Android. Really looking forward to it 😊

**Comment by ZayJackPrvy** [comment]
Hi @andrewtavis . I'd like to work on this issue. Could you please assign it to me?

**Comment by andrewtavis** [comment]
Hey @ZayJackPrvy 👋 Appreciate your interest in working with us! This issue's currently blocked a few issues in our data ingestion application. You'd be welcome to work on it after, which should be in a few weeks :) Is there another one you'd be interested in in that time?

**Comment by ZayJackPrvy** [comment]
@andrewtavis Yes. I would like to work on an issue that’s not too trivial, such as simple text changes or button adjustments. Could you recommend an appropriate issue for me? It's part of university course to contribute to an open-source project, and I’ve chosen your project. Hopefully it's OK for you.

**Comment by andrewtavis** [comment]
100% ok, @ZayJackPrvy! Thanks for letting me know as it's important for me to be able to provide the attention you'd need for it :) Can you tell me what the deadline is so I can keep it in mind? I'll look for some suggestions 😊

**Comment by ZayJackPrvy** [comment]
The deadline for the issue selection is until next week, but I can work on it much longer if needed.

**Comment by angrezichatterbox** [comment]
This issue could be unblocked right. If so I would like to work on this :)

**Comment by andrewtavis** [comment]
Unblocked and assigned! Glad to be able to finally start on all this, @angrezichatterbox!

**Comment by growabeard** [comment]
Beat me to it @angrezichatterbox!

**Comment by andrewtavis** [comment]
Closed by #277 🚀 Amazing to have this first Scribe feature added into the Android app! 🤖 Such a great moment for the application and the community 😊
