### ISSUE TITLE
Add emoji autosuggestion buttons to the keyboard UI

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#138]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that's needed for #66 is the buttons that would be used for autosuggestions. This issue would add these in. We'd like two different sets of buttons - one with two buttons for phones and one with three buttons for tablets. Each set should span the width of the third autosuggest button, and the distance between the emoji buttons should be the distance between the autosuggest buttons. 

The set of two buttons for phones should have buttons widths that are:

(WIDTH_OF_THIRD_AUTOSUGGEST_BUTTON - DISTANCE_BETWEEN_AUTOSUGGEST_BUTTONS) / 2

The set of three buttons for tablets should have buttons widths that are:

(WIDTH_OF_THIRD_AUTOSUGGEST_BUTTON - (DISTANCE_BETWEEN_AUTOSUGGEST_BUTTONS * 2)) / 3

The reason the distance between the autosuggest buttons is factored in twice for the tablet buttons is that we have three buttons and thus two spaces between them :)

For this issue we can color the buttons to show that they're present and available for use. The tablet buttons should be placed on top of the phone buttons so the phone buttons can be seen below. Both sets of buttons can be placed on top of the third autosuggestion button. We can make the tablet buttons red and the phone buttons orange for now, or just distinct colors.

### Contribution

Happy to support with this and review eventually, or can also work on it myself as is needed 😊

**Comment by Linfye** [comment]
I'd like to work on this issue. :)

**Comment by andrewtavis** [comment]
Thanks for your willingness to help here and take so much ownership of the emojis, @Linfye!

**Comment by Linfye** [comment]
I'm not quite clear where these emoji buttons should be added. Shouldn't the "third autosuggest button" be plural buttons"? Do you mean that the emoji buttons need to overlay the original buttons?

Could you please tell me more details about completing this issue? Thanks! 😊

**Comment by andrewtavis** [comment]
Yes these buttons should overlay the plural button. Basically when we need to show emojis we hide the plural button and deactivate it, and then we show and activate the emoji buttons 😊

**Comment by andrewtavis** [comment]
Closed by #158 🚀 Thanks so much for the hard work, @Linfye! Amazing work 😊
