### ISSUE TITLE
 Add in the small divider line between About options and Settings options without a description

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#139]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In Scribe-iOS there is a small line that separates the different items in the Table View when there is no description. This can be seen in the image given below.

<img width="300" alt="Screenshot 2024-09-22 at 10 54 54 AM" src="https://github.com/user-attachments/assets/94f5fd33-7f23-43eb-83f2-4ca8322d5562">

Currently, Scribe-Android does not separate the items in the Recycler View using a line when there is no description. This issue aims to add a line between items in a recycler view when there is no description. 

<img width="300" alt="Screenshot 2024-09-22 at 10 56 36 AM" src="https://github.com/user-attachments/assets/140b28e1-7e3c-442a-84e8-9973b3c268e6">

### Contribution

I would love to work on this and am more than willing to help anyone fix this issue :)

**Comment by MostafaMohamed2002** [comment]
can you assign this to me ?

**Comment by angrezichatterbox** [comment]
Feel free to work on this issue. In case of doubts don't hesitate to ask us. Thanks :)

**Comment by MostafaMohamed2002** [comment]
is this screenshot from settings fragment , after installing the keyboard ?
![image](https://github.com/user-attachments/assets/c0384191-2de2-4d4c-b93a-522085198ac9)

**Comment by andrewtavis** [comment]
That or the language of the application, @MostafaMohamed2002  :) Each should have a divider.

Would you want to work on this?

**Comment by MostafaMohamed2002** [comment]
should i make a pull request ?🤨 @andrewtavis @angrezichatterbox 
| | |
|---|---|
|![image](https://github.com/user-attachments/assets/c4dac462-2be2-4f93-8f50-9ab9592da105)|![image](https://github.com/user-attachments/assets/78b6f599-4a13-4e5b-ad7e-58ac1ce88c5c)|

**Comment by andrewtavis** [comment]
I'm kind of assuming that the differences in the pixel heights are maybe from the emulator, @MostafaMohamed2002? Aside from this, what's the color? If it's the text color, then it'd be great if it'd be the special text color that we use for the icon :) Can't tell exactly from the images.

**Comment by MostafaMohamed2002** [comment]
i will open a pr so we can dicuss more clearly
