### ISSUE TITLE
Add Description for App Language option in the settings page

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#142]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the app language option in settings does not have a description. The issue is to add a description to the app language option so that users can be more informed about its functionality.

<img width="389" alt="Screenshot 2024-09-22 at 2 14 47 PM" src="https://github.com/user-attachments/assets/694497e5-76d4-4081-921c-83ec5737a33a">

The above is how it is currently in Scribe-Android 

<img width="251" alt="Screenshot 2024-09-22 at 2 14 32 PM" src="https://github.com/user-attachments/assets/a43afb84-cd60-4618-81f3-31f9a756fc99">

This is how it should be added to the App Language option in the settings page. 

### Contribution

I would love to work on this and am more than willing to help anyone fix this issue :)

**Comment by catreedle** [comment]
Hello. I would like to work on this issue. @angrezichatterbox @andrewtavis

**Comment by andrewtavis** [comment]
Thanks for picking this up, @catreedle!

**Comment by andrewtavis** [comment]
Closed by #176 🚀 Hope you pick up more issues here soon, @catreedle! 😊
