### ISSUE TITLE
Remove right margin from the card view present in the Privacy Policy and Third Party Licenses page 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#144]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently the third party license page and the privacy policy page card view has a right margin. This causes the page to have an empty space towards the right. The issue is to remove the right margin so that the user interface would be much better. 

<img width="200" alt="Screenshot 2024-09-23 at 10 06 46 AM" src="https://github.com/user-attachments/assets/1047b0ac-2462-4f44-b860-aa4b998f4faf">

<img width="200" alt="Screenshot 2024-09-23 at 10 06 58 AM" src="https://github.com/user-attachments/assets/63b2218e-f945-4544-97e1-e51acbea1ee2">

As seen from above the texts don't go towards the right even though there is space. We have to remove that space from the right in the individual card view. 

### Contribution

I would love to work on this and am more than happy to help anyone fix this issue :)

**Comment by andrewtavis** [comment]
Closed by #168 🚀 Thanks, @henrikth93! 🥳
