### ISSUE TITLE
Version needs to be converted to an external link to directs towards the releases on GitHub

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#145]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The About page currently has a a version option under the Feedback and support Recycler view. The version option currently doesn't redirect to any page and has no action defined to it now. The issue aims to change the existing icon of the version page to showcase that it is to navigate to an external link as for the case of the see the code on GitHub option. and the option should be redirected to the Github Releases page of Scribe-Android.

Image references given below:

| Existing                                       | To be Changed to                                |
|-----------------------------------------------|------------------------------------------------|
| <img src="https://github.com/user-attachments/assets/2a41fed5-afb5-4e4f-a26c-2ae8cab63d90" width="389" /> | <img src="https://github.com/user-attachments/assets/09fb6202-7a50-4914-b883-01a994f5c703" width="389" /> |

Note: There are separate issues to add the divider. The issue is to change the version option third icon and add navigation to GitHub Releases Page

### Contribution

I would love to work on this and am more than happy to help anyone fix this issue :)

**Comment by DeKaN** [comment]
Hi, can I take the issue?

**Comment by andrewtavis** [comment]
By all means, @DeKaN! Looking forward to the contribution!

**Comment by DeKaN** [comment]
@andrewtavis Can you provide an example of the url? Should it be `https://github.com/scribe-org/Scribe-Android/releases/` or `https://github.com/scribe-org/Scribe-Android/releases/tag/<VERSION>` ?

**Comment by angrezichatterbox** [comment]
It should navigate to this URL https://github.com/scribe-org/Scribe-Android/releases/

**Comment by andrewtavis** [comment]
Closed by #169 🚀 Thanks for the feature, @DeKaN! Hope we can work with you again :)
