### ISSUE TITLE
Menu item to disable and enable period and comma on abc

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#147]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The issue would create a menu option for disabling and enabling period and comma on abc in the respective language keyboard settings.

The current individual keyboard settings does not have a Layout Recycler view so we would have create a Recycler view for layout items and then add the menu option for command and period on abc 

The below is the figma design for menu option. 

<img width="385" alt="Screenshot 2024-09-23 at 5 56 31 PM" src="https://github.com/user-attachments/assets/ec75b9f0-3eb4-405d-a946-1356f367654a">

### Contribution

I would love to work on this and am more than happy to help anyone fix this issue :)

**Comment by henrikth93** [comment]
I am interested in this one

**Comment by andrewtavis** [comment]
Nice @henrikth93 :) I'll assign this and the other one 😊

**Comment by andrewtavis** [comment]
Closed by #182 😊 Great to have such a large team over here now!
