### ISSUE TITLE
Disable Period and comma on ABC keyboard 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#148]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The issue aims to disable the period and comma in the individual keyboards. Currently Scribe Android has period and comma on all keyboard. The user would be given the choice to disable and enable this in the individual keyboard settings. This option is currently not functional. This issue is to add functionality to it and be able to disable and enable it accordingly. 

The issue is blocked by #147 where we would be creating menu option to disable the period and comma on abc. 

### Contribution

I would love to work on this and am more than willing to help anyone fix this issue :)

**Comment by henrikth93** [comment]
I am interested in this one

**Comment by andrewtavis** [comment]
Assigned, @henrikth93! We can unblock this one once, #147 is done :)

**Comment by MahmoudMabrok** [comment]
@henrikth93  are you able to start in this issue, as blocker is fixed now.

**Comment by andrewtavis** [comment]
Closed by #263 🚀 Thanks much for the great work here, @henrikth93, and also thanks for the notice that it was unblocked, @MahmoudMabrok!
