### ISSUE TITLE
Convert keyboard selection feature to separate keyboards

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#15]
### Terms

- [x] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [x] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As a part of #12, the way keyboards are selected needs to be changed so it matches Scribe-iOS. Not every user will need each keyboard, but some will need more than one, and eventually keyboards will be downloadable packs. Scribe-Android should thus include different keyboards, not a single one that can be changed to different languages. This will also allow for the settings icon to be removed from keyboards, which will save room for auto suggest and complete functionality as well as annotation features.

**Comment by angrezichatterbox** [comment]
I will start working on this issue

**Comment by andrewtavis** [comment]
Amazing, @angrezichatterbox! Really this would be amazing. Once this is done I'll make the issue for converting the application over to use a tab bar, and from there we'll be off to the races with making Scribe-Android a reality!

**Comment by angrezichatterbox** [comment]
Should the implementation of this be like Scribe-iOS where the user can select which all language scribe keyboards should be present and the accordingly  could change between them . Should I implemented this way by making the user select the keyboard he wants in the settings and then he could see those options pop up in input method picker when the user enables the keyboard

**Comment by andrewtavis** [comment]
Exactly, @angrezichatterbox :) We want to be enabling the keyboards individually, and then when the user uses the input method picker they would see the separate keyboards. Appreciate the dialog here!

**Comment by angrezichatterbox** [comment]
I am a little confused on its implementation I tried changing the method.xml for showing multiple languages and accordingly changing languages but I'm unable to implement or show multiple languages using that. The implementation of using a key for language works but that uses a dialog box I implemented. Any suggestion or tips for implementing multiple languages in the android input picker.

**Comment by andrewtavis** [comment]
I'm not sure about it for the Android input picker, @angrezichatterbox... In iOS we just have separate sub apps that are connected to the central application, with each of those being a keyboard input app. So Scribe itself for iOS is just a normal app, but then beneath it it has all of the various language keyboards that are then naturally added to the settings and able to be picked by the system input picker. Maybe this could be something to check to see if there's an Android equivalent? Aside from this, as I understand it there's now a key on the keyboard for switching languages? This could work for an initial release where in the settings tab we could give the user the option of which keyboard would be their default?

**Comment by angrezichatterbox** [comment]
I would look into the implementation so that we would be able to use the input picker itself.Its my first time working with the system input picker so I will try to implement within 2-3 days. Yes there is a key for changing language currently which loads up a dialog for selecting a language . This hasn't been implemented completely as I was trying to figure out the input method picker itself.

**Comment by andrewtavis** [comment]
Ok, all sounds fantastic, @angrezichatterbox, and please take your time :)

**Comment by angrezichatterbox** [comment]
So this is how I have implemented it for now . In the settings all the language would be present as in iOS and can enable which  language keyboard the user wants . When the enable keyboard is clicked the language Scribe keyboard would be present.Thanks for your insights I was able to get a better idea of how to implement it. Is the method I implemented the method that should be present ?

**Comment by andrewtavis** [comment]
This sounds good, @angrezichatterbox! I think we're ready for a PR and I can check it from there :) :)

**Comment by angrezichatterbox** [comment]
I have made the pull request . Please do tell me if there is any changes u want me to make after reviewing it.   :)

**Comment by andrewtavis** [comment]
Closed via #39 🚀🚀🚀🚀🚀 This is really amazing, @angrezichatterbox :) I'll be reaching out about a call in the coming days. Hope you have some availability, or we can schedule something for next week if not 😊
