### ISSUE TITLE
Settings Page Title Half Displayed after Switching to Dark Mode

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#151]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

After switching to dark mode, the title on the Settings page is cut off, displaying only "Settin". When you switch back to light mode, the title remains as "Settin". However, the title displays correctly if you navigate to a different page and then return to the Settings page.

![image](https://github.com/user-attachments/assets/335ed0f4-b183-4bc2-af88-774266937d55)

I currently do not know what caused this issue, nor when it occurred, but it is likely just a typo.

### Device type

Medium Phone API 35 in Android Studio Emulator

### Versions

Current development branch

**Comment by growabeard** [comment]
🖐️

**Comment by andrewtavis** [comment]
Thanks @growabeard! Let us know if we can help somehow :)

**Comment by andrewtavis** [comment]
Closed by #178 🚀 Thanks for the fix, @growabeard and also for the issue, @Linfye! 😊
