### ISSUE TITLE
Fixes to installation icon size and menu control

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#153]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to fix two minor issues from the work in #140. The current screen looks like:

![Screenshot_20240924_205853](https://github.com/user-attachments/assets/a5931189-9c91-4d80-8418-655ccc9fd8bf)

In this we'd like:
- The keyboard icon to be a little smaller so it fits the size of the text a bit better (say 80% smaller)
- As of now the user needs to press `Open keyboard settings` for the keyboard settings to open, but ideally this would occur if the user presses anywhere on the keyboard installation directions card :)

### Contribution

Happy to support with this or get to it myself eventually! 😊

**Comment by miaburns** [comment]
I would love to take this task!

**Comment by andrewtavis** [comment]
Sure thing, @miaburns! Let us know if you have any questions! 😊

**Comment by andrewtavis** [comment]
Closed by #199 😊 Thanks for your continued support of the project, @MostafaMohamed2002!
