### ISSUE TITLE
Preview Image in README.md appears vertically stretched in mobile view

### ISSUE THREAD

**Issue by has9sayed** [scribe-org/Scribe-Android#154]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

**Expected:**

The preview image in README.md should maintain its aspect ratio and display correctly across all devices, including desktop and mobile, without any distortion.

**Actual:**

The preview image displays correctly on the desktop view of GitHub but does not maintain its aspect ratio in both mobile browser view and GitHub mobile app, due to a fixed height of 512px. This affects the readability and aesthetics of the documentation.

### Github Mobile App view:

<img src="https://github.com/user-attachments/assets/6c4076e4-749b-44af-8048-656995ae260c" width="250"/>

### Mobile browser view:

<img src="https://github.com/user-attachments/assets/97c8bdb3-26b3-4afa-bf4c-93750dfc8520" width="250"/>

### Device type

Android

**Comment by andrewtavis** [comment]
Do you want to work on this, @has9sayed? :)

**Comment by andrewtavis** [comment]
Thanks much for the issue!

**Comment by has9sayed** [comment]
@andrewtavis Yes, I would like to work on this.

**Comment by andrewtavis** [comment]
Nice! Looking forward to the PR :)

**Comment by andrewtavis** [comment]
Appreciate you making the issue and executing so quickly, @has9sayed! 🚀
