### ISSUE TITLE
App is always dark mode on installation and switching to light mode crashes the app

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#155]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The app on installation is in dark mode. However, this is not visible on the settings page where the toggle for the dark mode is turned off by default. The issue is to make the toggle in dark mode in the launch. This is to prevent its crashing when switching the toggle in the earlier condition. 

A possible fix for this would be to turn the toggle default value for dark mode toggle to true. 

### Contribution

I would love to work on this and am more than happy to help anyone fix this issue :)

**Comment by andrewtavis** [comment]
Note that the keyboard also reflects some of these issues, with it being partial light mode and dark mode on first load.

**Comment by angrezichatterbox** [comment]
I would like to work on this issue until I can properly replicate #133 as I feel this could be a bug fix that should be fixed soon.

**Comment by andrewtavis** [comment]
Totally agree, @angrezichatterbox! Thanks for picking this up :)

**Comment by angrezichatterbox** [comment]
The keyboard bug was because, during the first launch, the keyboard view was designed to take in the value of the system's dark or light mode. I could do the same for all the pages and the toggle and have the toggle initial value and dark mode be based on whether the system is dark mode or should it be default dark mode. I guess having system color being taken initially better right?

**Comment by andrewtavis** [comment]
Yes, taking the system color initially would be best, @angrezichatterbox :)

**Comment by andrewtavis** [comment]
Closed by #157 🚀 Thanks for the great prioritization of issues, @angrezichatterbox!
