### ISSUE TITLE
Fix dark mode coloration for app screen

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#164]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

There are a few changes that should happen in the app to make dark mode match the [Figma designs](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=405-393&t=tALiQagal16aaDzj-1). Specifically:
1, On the installation screen below we want the `Quick tutorial` button to be a low opacity dark cta orange color (`D17B0F` with a 25% opacity) with a full opacity dark cta orange text and border (`D17B0F`)

![Screenshot_20241002_010422](https://github.com/user-attachments/assets/116b43ab-11bd-4fc7-b897-76ae74439072)

2. On the screen above and all others that have a corner icon like the Wikimedia and Scribe, privacy policy and third party licenses we'd like the corner icons to be the same low opacity dark cta orange above and the icon color can be dark cta orange

Please check the screen below for the appropriate designs:

![Keyboard Installation - Dark](https://github.com/user-attachments/assets/437b7004-3a87-40bd-ad00-2e1a62b68d60)

### Contribution

Happy to support with this issue as needed! I can review the PR for the work or also answer questions as needed :) This is a great `good first issue`!

**Comment by growabeard** [comment]
I'd like to try working on this, if that's alright.

**Comment by andrewtavis** [comment]
Thanks for your willingness to help, @growabeard! Please let us know if there's anything we can do to help :)

**Comment by andrewtavis** [comment]
Closed by #170 :) Thanks for a great first contribution, @growabeard!
