### ISSUE TITLE
Rate Scribe needs an action

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#165]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The Rate Scribe Option in the About Page currently doesn't have an action. The option has been implemented to be rated in either F-Droid or in the Google Play store depending on where it is being installed from. 

### Contribution

I would love to work on this and am more than willing to help anyone solve this issue.

**Comment by MostafaMohamed2002** [comment]
can we do it before you upload the app to playstore ??

**Comment by angrezichatterbox** [comment]
I am not sure about F-Droid. We could create the function for it as we can use the app identifier for the Play Store URL that would not change on the app release. I am not about how it would function before release.

**Comment by henrikth93** [comment]
I have done some on this. Gonna contact you later @angrezichatterbox

**Comment by andrewtavis** [comment]
Ya for this maybe we can comment out the code for the the actual Play store and F-Droid actions and leave the toast for now, but still have the code that we need once we have the URLs :)

**Comment by andrewtavis** [comment]
I guess we can close for now and do another issue later when we have the URLs :) Closed in #187. Thanks @henrikth93!
