### ISSUE TITLE
Reset Hints needs to be Implemented

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#167]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

After #166 We would have implemented app hints for installation, settings, and about pages. The option on the About page for resetting settings is currently not functional. The app hints are only visible to the user on the first launch and after clicking ok would not be visible to the user. The reset app hints should make the app hints again visible for the user until the user clicks ok. 

- **Note:** The issue is being blocked by #166 where we would bring the app hints for the pages.

### Contribution

I am happy to work on this and am more than happy to help anyone solve this issue.

**Comment by andrewtavis** [comment]
Thanks for the attention you're giving the issue tags, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Closed by #193 :) Thanks @ZayJackPrvy!
