### ISSUE TITLE
Autosuggest Emojis Switch Status Not Saved Across Languages in Language Settings

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#186]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

After setting Autosuggest Emojis and returning to the Settings page, the switch status is reset to the default state, but this issue does not exist for the Double Space Peroids switch.

### Device type

Medium Phone API 35 in Android Studio Emulator

### Versions

 The latest main branch

**Comment by andrewtavis** [comment]
Thanks for the issue, @Linfye!

**Comment by andrewtavis** [comment]
As I remember this is also closed by #158, @Linfye :) Let us know if there's any further work here and we can reopen it if so 😊
