### ISSUE TITLE
Add unit tests to PR Checks for Scribe Android

### ISSUE THREAD

**Issue by albendz** [scribe-org/Scribe-Android#195]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

# Summary

Unit tests can be run with commands `./gradlew test` or `./gradlew check`. Note that the `check` task will also run other things like detekt. This issue tracks adding running these commands as part of PR checks.

This will be added to the `./github/workflows` folder with the other PR workflows.

One question is whether the unit tests should be merged with the ktlint PR workflow or kept separate.

### Contribution

I can work on this one. Feel free to assign to me with the recommendation on whether to merge this with the detekt PR workflow or have separate.

**Comment by albendz** [comment]
I can pick this one up!

**Comment by andrewtavis** [comment]
Thanks for picking it up, @albendz! :) :)

**Comment by Linfye** [comment]
@andrewtavis Can this issue be closed by #209? 😊

**Comment by andrewtavis** [comment]
Can be, yes @Linfye :) Thanks for the note and for the contributions, @albendz!
