### ISSUE TITLE
Add code coverage for unit tests to Scribe Android

### ISSUE THREAD

**Issue by albendz** [scribe-org/Scribe-Android#196]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

# Summary

Add support to output and check unit test coverage as part of the test gradle task.

If possible, add functionality where there is a github action or workflow that automatically shows the resulting code coverage as a PR comment.

Initially, the task should not fail the build on low code coverage and later on it can be enforced. A reasonable code coverage threshold will need to be chosen for this. I suggest 60% as a starting target.

## Additional Details

This most likely involves adding Jacoco dependencies and tasks in the gradle files: https://docs.gradle.org/current/userguide/jacoco_plugin.html

Example of something that puts Jacoco coverage on PRs: https://github.com/marketplace/actions/jacoco-report

### Contribution

I can pick this up later if no one else has grabbed it before me. I'll comment when I'm ready to take it on if it's still available.

**Comment by albendz** [comment]
I can pick this up

**Comment by andrewtavis** [comment]
Thanks for the help here, @albendz!

**Comment by andrewtavis** [comment]
Leaving this open for the issue that the PR comment addition from @MahmoudMabrok can reference :)
