### ISSUE TITLE
Add double space period shortcut

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#20]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The double space period shortcut will need to be added to Scribe-Android before the initial release, as this is a valuable technique that users will expect. This issue is for finding where it should be added and implementing the change.

Ideally this would also include an option in the settings to disable this feature, but this can be done later in another issue.

### Contribution

I'll work on this if others don't have interest. This should definitely be included in the 1.0.0 release.

**Comment by Jk40git** [comment]
@andrewtavis I have interest on this 👍 !

**Comment by andrewtavis** [comment]
Hey @Jk40git 👋 Great to hear that you have interest in Scribe-Android :) For now let's stick to Scribe-Data as we're not really focussing here right now, and the goal of GSoC is to work on Scribe-Data.

**Comment by Jk40git** [comment]
> Hey @Jk40git 👋 Great to hear that you have interest in Scribe-Android :) For now let's stick to Scribe-Data as we're not really focussing here right now, and the goal of GSoC is to work on Scribe-Data.

All right 👍

**Comment by angrezichatterbox** [comment]
Could I work on this issue and is it still available to be solved or is it already solved ?

**Comment by andrewtavis** [comment]
Sure thing, @angrezichatterbox! Let me know if there's anything I can do to support :)

**Comment by angrezichatterbox** [comment]
I have made the double space period shortcut should I also add the option in settings to disable and enable this shortcut

**Comment by andrewtavis** [comment]
Ya that'd be perfect, @angrezichatterbox! Thanks for checking in and going the extra mile!

**Comment by angrezichatterbox** [comment]
I have implemented the things as mentioned but I have some doubts

**Comment by angrezichatterbox** [comment]
I have implement the period on checkbox enabling only . I have one doubt the period should only come when there is text before the double tap on space bar right

**Comment by andrewtavis** [comment]
Yes, that sounds great, @angrezichatterbox!

**Comment by angrezichatterbox** [comment]
Is there any function to check for text before cursor or I have to make one by using the input connection in SimpleKeyboardIME.KT.

**Comment by andrewtavis** [comment]
I think you'd need to make the function yourself. And that file should be renamed as well given that it's related to the project that Scribe Android is based on :)

**Comment by angrezichatterbox** [comment]
I have created a pull request adding this feature do check it whenever you're free . I am ready to make changes as required.

**Comment by andrewtavis** [comment]
Thanks, @angrezichatterbox! Will check this and the other PR as soon as I can :)

**Comment by andrewtavis** [comment]
Closed by #36 😊 Thanks a lot for this, @angrezichatterbox! Really great to have a feature in here after so long. I'm set up to be able to review now, so feel free to work on stuff. Maybe from here you can provide some feedback on #34, and then after that we can look to do a call if you'd still like to work on things?

Again, thanks so much!
