### ISSUE TITLE
Remove the unused code from the codebase

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#200]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the app has a lot of unused code or code that has been used in the application but has not impacted on the functionality of the application. Removal of such code is essential as it helps increase the build speed of the application. 

The removal would include manual removal and using existing lint checks to improve the removal of unnecessary code from the application. 

### Contribution

I will be working on this issue :)

**Comment by andrewtavis** [comment]
Thanks @angrezichatterbox! This will really help reduce the code down and make it easier for people to work with :)

**Comment by Linfye** [comment]
@andrewtavis Can this issue be closed by #204, or is there still unfinished work? 😊

**Comment by andrewtavis** [comment]
I think it can be, yes @Linfye :) Thanks for checking old issues!
