### ISSUE TITLE
Select language recycler view increases and decreases it size on page change

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#205]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When navigating away from the settings page, the RecyclerView displaying the keyboard language selection experiences an unexpected change in size. This issue only resets when the user toggles between dark and light modes or reopens the app.

Steps to Reproduce:

1. Open the settings page.
2. Navigate to any other page.
3. Observe the size change of the keyboard language RecyclerView.

**Before:**

<img width="200" alt="Screenshot 2024-10-17 at 8 34 41 PM" src="https://github.com/user-attachments/assets/3c314090-8780-434b-8a9a-6a2bef605d79">

**After:**

<img width="200" alt="Screenshot 2024-10-17 at 8 35 24 PM" src="https://github.com/user-attachments/assets/9c1da248-5774-4455-ac77-eb2f82ccfd13">

### Device type

Pixel 8

**Comment by angrezichatterbox** [comment]
This is a bug that I have noticed recently. I would like to work to fix the bug.

**Comment by andrewtavis** [comment]
Closed by #208 🥳 Thanks you, @angrezichatterbox!
