### ISSUE TITLE
 App does not exit when back button is pressed

### ISSUE THREAD

**Issue by AshiqYadav** [scribe-org/Scribe-Android#206]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When pressing the back button while on the first page of the app, the app does not exit as expected. Instead, it stays on the current screen. This is not user-friendly, as users expect the app to close or minimize when they press the back button on the main screen.

https://github.com/user-attachments/assets/e57e795e-ea0d-46f4-aa98-6897d118d160

* Please assign me this issue under `hacktoberfest`

### Device type

Realme 8

### Versions

Android version - 13 and scribe version - latest

**Comment by andrewtavis** [comment]
Thanks for the issue, @AshiqYadav :) We're in the midst of all kinds of things to get an MVP out, so really appreciate you finding these issues and being willing to work on them 😊

**Comment by andrewtavis** [comment]
Closed by #207 :) Thanks a lot for the issue and getting to it so quickly, @AshiqYadav! Would be great to work with you again 😊
