### ISSUE TITLE
Home Screen Flickering

### ISSUE THREAD

**Issue by wasif1** [scribe-org/Scribe-Android#210]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

On application home screen, the screen is flickering
[Screen_recording_20241018_234912.webm](https://github.com/user-attachments/assets/4178689e-f673-4baa-baed-32831fe9424c)

### Device type

Emulator Pixel 5 API 33

### Versions

Android 13 and 1.0.0(7)

**Comment by andrewtavis** [comment]
Thanks for the issue! Would you have interest in looking in to this, @wasif1?

**Comment by andrewtavis** [comment]
I think we'll certainly need to keep using emulators, but I agree that this isn't something we can do anything about. I'll close this :)

**Comment by andrewtavis** [comment]
Thanks for the investigation, @Linfye, and also for the issue, @wasif1!
