### ISSUE TITLE
Use Gradle Caching in GitHub Actions Workflows 

### ISSUE THREAD

**Issue by MostafaMohamed2002** [scribe-org/Scribe-Android#212]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

I suggest adding **Gradle caching** to the GitHub Actions workflows to reduce build times and improve CI/CD efficiency. 

### Contribution

i can take on this issue :)

**Comment by andrewtavis** [comment]
Thanks for the issue and for taking it on, @MostafaMohamed2002! :)

**Comment by andrewtavis** [comment]
Closed by #218 :) Thanks so much, @MostafaMohamed2002!
