### ISSUE TITLE
Migrate XML layouts present in the frame layout to Jetpack Compose

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#217]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need to migrate the existing XML layouts within the FrameLayout to Jetpack Compose. This will help us leverage Compose's benefits, such as better performance and easier UI management. The layouts currently present in the frame layout of the main activity are the Wikimedia Scribe Page, Privacy Policy page, and Third-party License page.  

The issue aims to convert those existing views to JetPack compose and replace the frame layout with a compose view in the activity main XML. 

**Reference material**

- Jetpack Compose documentation: [Jetpack Compose Docs](https://developer.android.com/jetpack/compose)

### Contribution

Happy to help others fix this issue or take this up at some point :)

**Comment by growabeard** [comment]
I wonder if this should be all the views at once or if they should be split up?

Either way I'd love to throw my hat in the ring.

**Comment by andrewtavis** [comment]
Thanks @growabeard! Great to get some progress on these Jetpack Compose issues :)

**Comment by andrewtavis** [comment]
Would you have interest in doing the same for the privacy policy and the Wikimedia and Scribe page, @growabeard? Including getting rid of the corner triangles would also be great 😊 Let us know!

**Comment by growabeard** [comment]
Oh yes I failed to mention that in my PR description. My intention was to do the initial work and get feedback before I followed up with the other views in a single PR. Does that work?

**Comment by andrewtavis** [comment]
Sounds great to me :) Looking forward to it!

**Comment by andrewtavis** [comment]
Closed by #258, with further work continuing in #256 :) Thanks for the great work as always, @growabeard! 🚀
