### ISSUE TITLE
Deleting an Emoji Requires Two Backspaces

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#226]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

In the current version, deleting an emoji requires pressing backspace twice due to the way emojis are encoded.

### Device type

Medium Phone API 35 in Android Studio Emulator

### Versions

The latest main branch

**Comment by Linfye** [comment]
I'd like to work on this. 😊

**Comment by andrewtavis** [comment]
Thanks for the issue and the dedication to emojis, @Linfye! :)

**Comment by andrewtavis** [comment]
Can you set the button color to transparent in the work for this one as well, @Linfye? Would be a nice step to getting it to a more final state :)

**Comment by Linfye** [comment]
> Can you set the button color to transparent in the work for this one as well, @Linfye? Would be a nice step to getting it to a more final state :)

👌

**Comment by andrewtavis** [comment]
Closed by #229 😊 Thanks for this, @Linfye! Great to have this functionality be so responsive and what the user would expect :)
