### ISSUE TITLE
Language Settings Switches Doesn't Work

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#231]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Currently, the Settings button cannot control the toggling of the Emoji Autosuggest and Double Periods features. I'm not sure when these bugs appeared; I guess it may have been during the previous simplification and refactoring process.

### Device type

Medium Phone API 35 in Android Studio Emulator

### Versions

The latest main branch

**Comment by andrewtavis** [comment]
Closed by #235 🚀 Really appreciate the issue and the work to clear it up, @Linfye!
