### ISSUE TITLE
Language Settings UI Items duplicated

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#232]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

As shown in the image below, the Autosuggest Emojis and Double Space Periods items appear duplicated in both the Functionality and Layout lists.

![PixPin_2024-10-29_08-55-43](https://github.com/user-attachments/assets/641efc63-3472-4062-bcf8-9a6183bbca16)

### Device type

Medium Phone API 35 in Android Studio Emulator

### Versions

The latest main branch

**Comment by andrewtavis** [comment]
Closed by #233 🥳 Thanks for the issue and fixing it, @Linfye!
