### ISSUE TITLE
Move installation corner to the left when menu language is RTL

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#239]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in an optional top left corner triangle for the installation screen of the menu for RTL languages. As Arabic is the only RTL language in Scribe-i18n at this time, the menu should check to see if Arabic has been selected and then switch the corner triangle if so. The current interface can be seen here:

![Installation Directions](https://github.com/user-attachments/assets/2683cace-986e-4eaf-90e8-7b90ab0c0226)

### Contribution

Happy to support with this and review when a PR is up! Can also work on it myself if needed 😊

**Comment by Linfye** [comment]
I'd like to work on this. 😊

**Comment by andrewtavis** [comment]
Nice, @Linfye! Feel free to use the [update_i18n_keys.sh](https://github.com/scribe-org/Scribe-Android/blob/main/update_i18n_keys.sh) script to bring over the latest version of Scribe-i18n into the project 😊

**Comment by andrewtavis** [comment]
Leaving this open for now until we bring in the localizations, @Linfye :)

**Comment by andrewtavis** [comment]
@Linfye, we now have the Arabic strings in the repo. Can you pull them down and check that the changes in #241 are working? :)

**Comment by Linfye** [comment]
> @Linfye, we now have the Arabic strings in the repo. Can you pull them down and check that the changes in #241 are working? :)

 OK, I'll do this later today. 😊

**Comment by Linfye** [comment]
@andrewtavis  It works fine for me. :)
![PixPin_2024-11-17_21-46-18](https://github.com/user-attachments/assets/b54f73b7-68e9-4f2a-b4c5-e9930a7fca8d)
And do we need to mirror the right_arrow icon in RTL layout? This icon displays on sevral pages.

**Comment by andrewtavis** [comment]
Nice, @Linfye! Ya that change would be great :) Can you send along a PR for it?

**Comment by Linfye** [comment]
> Nice, @Linfye! Ya that change would be great :) Can you send along a PR for it?

Yes, I'd love to after solving #160. 😊

**Comment by andrewtavis** [comment]
Nice! Thanks so much for following through with this issue till the end! 🚀

**Comment by Linfye** [comment]
> Nice! Thanks so much for following through with this issue till the end! 🚀

I've sent a PR for this and I noticed that the string Version is not added to i18n which is untranslated in all current languages. 😊

![PixPin_2024-11-18_23-19-14](https://github.com/user-attachments/assets/7c1204b5-456b-4dec-b796-9eaee706b748)

**Comment by andrewtavis** [comment]
Ah great! I'll fix this :) Thanks, @Linfye!

**Comment by andrewtavis** [comment]
59f9c35 fixes the issue where the localization for Version wasn't being picked up :) Beyond this #249 brings us to a close here 😊 Thanks, @Linfye! 🚀
