### ISSUE TITLE
Add border to the keyboard keys

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#24]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add a border to keyboard keys. The location of the keys will be more apparent and the overall look of Scribe-Android will be improved by adding them.

Help on this would be much appreciated!

**Comment by IunaIuna** [comment]
Hello! I am new to open source and want to participate in Hacktoberfest. I would like to work on this issue.

Cheers
Iuna

**Comment by andrewtavis** [comment]
Hi @IunaIuna! Welcome to open-source! 😊 Didn't know about Hacktoberfest myself until you and a contributor for iOS mentioned it. This is really great!

I'd be happy to assign this to you and give support as I can. Feel free to reach out with questions :)

All the best!

**Comment by andrewtavis** [comment]
A quick note, @IunaIuna, I've just finished up #22, which changed the codebase a ton as lots of files got removed and moved around. Would be good for you to do a pull of the most recent version 😊

Let me know if you're hitting any roadblocks :)

**Comment by IunaIuna** [comment]
Hi! Thanks for letting me know. just synced the fork.
I'm currently trying to find out where the xml defining the keyboard is located (never worked on any custom keyboards before).

**Comment by andrewtavis** [comment]
Great :) There were a few changes in the hour before you synced, so I'm glad I was able to get those in before 😊

As for as the `.xml` is concerned, I'm not sure if that'll be necessary for this issue. The keys are all put in programmatically based on dimensions of the screen. I'm going to bed now, but I'll check in tomorrow and see if I can direct you to where the change should happen 😊

**Comment by andrewtavis** [comment]
Morning! ☀️

Looking into it all, the `Keys` class in [MyKeyboard.kt](https://github.com/scribe-org/Scribe-Android/blob/248c40acf603cfce92a172a6337b951ec94b08af/app/src/main/kotlin/org/scribe/helpers/MyKeyboard.kt#L123) would be a good place to start, as well as this part of [KeyboardView.kt](https://github.com/scribe-org/Scribe-Android/blob/7bf8ed5237df02fcb658892b644b1e6b2e222e05/app/src/main/kotlin/org/scribe/views/MyKeyboardView.kt#L450) where the backgrounds of keys are set (the commented out part is some attempts I made earlier to work on this during a hackathon 😊). 

As an aside, sorry that there's not as many comments in all of this as there should be. I'm working off of a base keyboard project, and will be using #18 to go through and improve the readability :)

**Comment by ayushanand308** [comment]
@IunaIuna @andrewtavis  Are you still working on this? If not can I be assigned this?

**Comment by andrewtavis** [comment]
@ayushanand308, you'd be welcome to work on this :) I'd be happy to reassign to you in a few days if @IunaIuna has no issues with it 😊

Thanks for reaching out!

**Comment by andrewtavis** [comment]
Closed by @angrezichatterbox in #36 :) Thanks for working on this! Great to have someone working more consistently on Scribe-Android :)
