### ISSUE TITLE
building app failing duo to missing string resource 

### ISSUE THREAD

**Issue by MahmoudMabrok** [scribe-org/Scribe-Android#243]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

pipeline failed to build app duo to missing string resources. 

https://github.com/MahmoudMabrok/Scribe-Android/actions/runs/11871381606/job/33083823181#step:4:78

### Device type

NA

### Versions

Latest

**Comment by andrewtavis** [comment]
Thanks for the issue, @MahmoudMabrok! Definitely unexpected given Scribe-i18n is at 100% across all languages in the most recent import. CC @angrezichatterbox :)

**Comment by MahmoudMabrok** [comment]
it was building app before normally, but now it keeps failing.

**Comment by MahmoudMabrok** [comment]
I tried tp do dummy pr and check current workflow and it fails also. 
check [here](https://github.com/MahmoudMabrok/Scribe-Android/actions/runs/11871440501/job/33083955591#step:4:77) and [here](https://github.com/MahmoudMabrok/Scribe-Android/actions/runs/11871440498/job/33083955589?pr=2#step:5:137)

**Comment by angrezichatterbox** [comment]
> Thanks for the issue, @MahmoudMabrok! Definitely unexpected given Scribe-i18n is at 100% across all languages in the most recent import. CC @angrezichatterbox :)

For now, the Gradle task does not move from the i18n folder to the res. I will look into it and make a quick fix by tonight.

**Comment by angrezichatterbox** [comment]
The issue must have occurred during the time I made the conversion from build.gralde to build.gradle.kts. Thanks @MahmoudMabrok for finding this issue.

**Comment by MahmoudMabrok** [comment]
the issue is [here](https://github.com/scribe-org/Scribe-Android/commit/8c70a6a9dc812dbe339c3b855cd3c8025c262bf9#diff-1c5d103c04afd91ef1dc29f75921c46985eeafcedf2b88b7bfedf61a0914db48L52) this string  is removed.
