### ISSUE TITLE
Migrate the Main Activity to Jetpack Compose 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#246]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Refactor MainFragment to replace its current UI setup with Jetpack Compose while integrating ViewPager2 to manage pages within the activity. This will allow us to handle Compose-based UI inside each page of the ViewPager2 until all fragments are fully converted to Compose-based alternatives. 

This issue is to set an example of how we would use existing fragments to handle the compose the view pager to not break the app during the conversion.

### Contribution

I will be working on this issue :)

**Comment by andrewtavis** [comment]
Closed via #250 :) Thanks much for the quick work here, @angrezichatterbox! 🚀
