### ISSUE TITLE
Migrate the settings page to Jetpack Compose 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#247]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current Settings page is implemented using XML and a Fragment. This issue involves migrating the Settings page to Jetpack Compose. The goal is to replace the XML layout with a Compose-based UI and update the fragment's content view to use Compose. This ensures that the app remains functional throughout the migration, and `ViewPager2` continues to work during the process.

The migration will replace `RecyclerView` with Compose alternatives like `LazyRow` and `LazyColumn`, removing the need for the existing adapter. For more details on handling `LazyRow` and `LazyColumn`, refer to [this document](https://developer.android.com/develop/ui/compose/lists).

### Contribution

Happy to support in solving this issue or take this up :)

**Comment by angrezichatterbox** [comment]
I will be working on this issue. @Jag-Marcel I would solve this issue and make a PR in a day or two. It would give some more idea on the exact change to be done for the conversion of XML to Compose and what exactly needs to be done for #248

**Comment by Saifuddin53** [comment]
Hello, @angrezichatterbox if you haven't yet started this migration then can I work on it?

**Comment by angrezichatterbox** [comment]
I have started working on this issue for now and would make a PR in a day or two. Would you like to check out some of the other issues.

**Comment by Saifuddin53** [comment]
Sure! I'm definitely interested @angrezichatterbox, but I'd be especially keen to work on any issues related to migrating to Jetpack Compose if there are any.

**Comment by Saifuddin53** [comment]
@angrezichatterbox can I create an issue for migration of privacy policy screen and then start working on it?

**Comment by angrezichatterbox** [comment]
The page is already being worked on at the moment. Depending on the requirement the language settings page might need a separate issue but I'm not sure for now as it might be completed within this issue if we could reuse the existing created components. I'll be creating the issue for the language settings page if it's needed in the next few days.

**Comment by Saifuddin53** [comment]
Okay no problem I would like to work on any other issue as well

**Comment by angrezichatterbox** [comment]
Would you like me to suggest you some issues to checkout :)

**Comment by Saifuddin53** [comment]
I have checked some issues but most of them are assigned to someone else. Do you mind If I comment there? 🙂

**Comment by angrezichatterbox** [comment]
If an issue has been assigned long back. You could ask the assignee if he would be interested to hand the issue over to you. Or else you could take a look into [Add in all needed interface variable strings to the keyboard constants](https://github.com/scribe-org/Scribe-Android/issues/214) , and the linting issue leftover. These are good first issues.

**Comment by angrezichatterbox** [comment]
> Okay no problem I would like to work on any other issue as well

I’ve created a new issue for the Language settings page once the other issue is resolved and if the new issue is left unassigned. Please feel free to work on it.

**Comment by andrewtavis** [comment]
Closed by #252 🚀 Looking forward to bringing in the data and making the keyboard issues we mapped out, @angrezichatterbox! Hopefully Sunday 😊
