### ISSUE TITLE
Migrate the About Page to Jetpack Compose

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#248]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current About page is implemented using XML and a Fragment. This issue involves migrating the About page to Jetpack Compose. The goal is to replace the XML layout with a Compose-based UI and update the fragment's content view to use Compose. This ensures that the app remains functional throughout the migration, and `ViewPager2` continues to work during the process.

The migration will replace `RecyclerView` with Compose alternatives like `LazyRow` and `LazyColumn`, removing the need for the existing adapter. For more details on handling `LazyRow` and `LazyColumn`, refer to [this document](https://developer.android.com/develop/ui/compose/lists).

### Contribution

Happy to support in solving this issue or take this up myself :)

**Comment by angrezichatterbox** [comment]
@Jag-Marcel This could be an issue that could be good to get into Jetpack Compose. Happy to help in whatever way possible :)

**Comment by Dezzy12** [comment]
Hello,

I am new to Jetpack Compose and Android development, and I am eager to expand my knowledge by contributing to open source projects. If possible, I would like to collaborate on this issue.

Thank you!

**Comment by andrewtavis** [comment]
Sure thing, @Dezzy12! Assigned and looking forward to the contribution :) Please let us know if you need any support!

**Comment by Dezzy12** [comment]
Cool, Let me get to setting up. I'll let you know if I encounter any issues

**Comment by nebadesmondc** [comment]
Hello, @Saifuddin53 Yes you can.

**Comment by andrewtavis** [comment]
Thanks for passing it over, @nebadesmondc! Hope to work with you on another issue sometime :) 

@Saifuddin53, I would say let us know if you need help here normally, but then I see you have the PR up already 😊 Looking forward to the review!

**Comment by angrezichatterbox** [comment]
Closed by #260. Thanks for your fantastic work, @Saifuddin53. We hope to see you contribute more to the project.

**Comment by andrewtavis** [comment]
@Saifuddin53, we also have our bi-weekly developer sync that maybe you'd have interest in! It's every two Saturdays at 15:00 UTC. The next would be December 14th :) Would be great to have you join 😊

**Comment by Saifuddin53** [comment]
Thank you for the invite, would love to join @andrewtavis 🙂
