### ISSUE TITLE
Add dark and light mode responsiveness

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#27]
### Terms

- [x] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [x] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to implement color color scheme switching between light and dark modes.

- This issue is blocked by #25 as the schemes should be created before this issue

**Comment by ayushanand308** [comment]
@andrewtavis This seems a good feature. Will be working on it :).

**Comment by andrewtavis** [comment]
Hey @ayushanand308! Thanks for your interest in Scribe! Yes I think this would be a great feature to better understand the project 😊

I'll assign this to you, and please let me know if you have any questions!

**Comment by ayushanand308** [comment]
@andrewtavis sure!

**Comment by ayushanand308** [comment]
@andrewtavis Basically what I understand from the task description is that I have to implement a way to switch between dark and light themes on the keyboard right?

**Comment by ayushanand308** [comment]
![WhatsApp Image 2023-03-01 at 00 24 47](https://user-images.githubusercontent.com/99035102/221951891-e5b5a478-3e67-4cb2-b674-5ff87ed5f46d.jpg)



Thinking of implementing it like this. Is this ok?

**Comment by andrewtavis** [comment]
Yes, exactly @ayushanand308! Specifically it would also be good if the default was set based on the mode of the user’s phone. Not sure if you have an idea on how best to do that, and I could support with exploration if needed :) So if the user has dark mode on their phone, it would be great if the option was already selected for them 😊

**Comment by ayushanand308** [comment]
@andrewtavis I would surely ask for help wherever I need it.

**Comment by andrewtavis** [comment]
Wonderful, @ayushanand308 :) Looking forward to the results! 😊

**Comment by ayushanand308** [comment]
@andrewtavis 
I am not able to understand how to add functionality to this dark theme checkbox toggle like there is for "vibrate on keypress" and others. Can you help with this.:-)

https://user-images.githubusercontent.com/99035102/222565267-8374282c-f3d2-45a1-8279-1c961c63bb74.mp4

**Comment by andrewtavis** [comment]
Hi @ayushanand308! Just wanted to write that I have this in mind. Currently visiting family at the moment :)

**Comment by ayushanand308** [comment]
@andrewtavis  We can get back to this later on 😊.

**Comment by ayushanand308** [comment]
https://user-images.githubusercontent.com/99035102/224350948-1bb26a91-aa85-42a5-a0e3-e1ec831171c1.mp4

The functionality of default theme being set to the user's default is done.

**Comment by andrewtavis** [comment]
Wonderful, @ayushanand308!! Sorry I haven’t been responsive. I’m in the midst of lots of family visits and have a wedding today, so really have been busy. Appreciate you getting to this and your dedication! I’m done with this trip Monday evening and will connect with you then. 

Thanks again so much 😊

**Comment by ayushanand308** [comment]
@andrewtavis  Apologies for responding so late, I was caught up in my semester exams.
I also wanted to ask if I can submit a GSOC proposal regarding scribe project to you for review before final proposal submission for any type of feedback.

**Comment by andrewtavis** [comment]
No stress, @ayushanand308! Do you want to send a PR with the work you did so far and we can figure out how to apply it to the keyboard? :)

As far GSoC, you're welcome to send along a proposal to me! You can reach me at my email in my profile here, and feel free to join us in the [Matrix space](https://matrix.to/#/#scribe_community:matrix.org) we made for Scribe (there's a room for GSoC and others like Android).

**Comment by ayushanand308** [comment]
@andrewtavis  I have sent a PR. Can you review it and tell me if you want any changes. :-)

**Comment by andrewtavis** [comment]
Thanks, @ayushanand308! Will check it later today 😊 Looking forward to seeing how it's changed :)

**Comment by andrewtavis** [comment]
Note for this issue that #33 got dark mode working for Xiaomi Redmi 9. I was not able to reproduce on the latest Pixel, but that PR was merged for the interim progress. Thank you @ayushanand308! As I said in the PR, appreciate the code that you wrote and your willingness to help on all this. I'm sorry I couldn't focus on this as much as I could.

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋 Do you want to write in here so I can assign for you looking further into this one?

**Comment by angrezichatterbox** [comment]
Ya sure .. I would work on this issue .

**Comment by angrezichatterbox** [comment]
The keyboard color should also change according to the current color scheme present in the schema for nightly and normal right

**Comment by andrewtavis** [comment]
Yes ideally that keyboard color would also change. We can work on the specifics of the colors later when we do the color action of the special keys, so for now just make the keys black and the background a different grey :)

**Comment by angrezichatterbox** [comment]
I have made the pull request please do tell if there are any changes to make I would be happy to make it perfect if there are any flaws.

**Comment by andrewtavis** [comment]
Thanks, @angrezichatterbox! You really are making some progress here!

**Comment by andrewtavis** [comment]
I'll check this tonight :)

**Comment by andrewtavis** [comment]
Closed by #38 🥳🙌 Thanks so much for all the consistent work, @angrezichatterbox! Really amazing 😊 I'll write to you on Matrix for the next steps :)
