### ISSUE TITLE
Add license tag to the top of all Kotlin files

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#282]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As Scribe-Android is a GPL-3.0 licensed project, we need to include the license tag at the top of each file in the repository. This isn't necessarily the easiest for files in formats like XML, but for Scribe-iOS we've decided to include the short license at the top of all `.swift` files. We should follow the same convention for Scribe-Android with Kotlin files :)

- See [Scribe-iOS/Scribe/AppDelegate.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Scribe/AppDelegate.swift) for an example of the license that we'd like to include as well as a description of the file

This is a great good first issue for someone wanting to help with Scribe-Android! ✨😊

**Comment by mat-in** [comment]
Added license to all .kt files. Please ask if needed additional configurations.

**Comment by andrewtavis** [comment]
See my message in the now closed PR, @mat-in :) Please let us know if you need some assistance!

**Comment by MostafaMohamed2002** [comment]
is there any chance to assign this to me ?

**Comment by andrewtavis** [comment]
#284 was opened for this, @MostafaMohamed2002 :) Feel free to let us know if there's another issue you'd like to work on! 😊

**Comment by MostafaMohamed2002** [comment]
Oh , i didn't notice that there is a new pr already open 😔 , i think i can help with something else 😀

**Comment by andrewtavis** [comment]
Looking forward, @MostafaMohamed2002! 🚀

**Comment by andrewtavis** [comment]
Closed by #284 :) Thanks a lot for taking this on and getting it finished up in such a timely manner, @mat-in! Really great to have the codebase be more compliant with the license.

CC @angrezichatterbox: I did my best to edit the file descriptions at the top of the files, but ultimately you know best on these things. Maybe you could take a moment to check them and send a commit with edits to make them a bit more clear to what all the files are exactly doing?

**Comment by angrezichatterbox** [comment]
> Closed by #284 :) Thanks a lot for taking this on and getting it finished up in such a timely manner, @mat-in! Really great to have the codebase be more compliant with the license.
> 
> CC @angrezichatterbox: I did my best to edit the file descriptions at the top of the files, but ultimately you know best on these things. Maybe you could take a moment to check them and send a commit with edits to make them a bit more clear to what all the files are exactly doing?

I will look into it and check if any changes are required.
