### ISSUE TITLE
Update App UI to a tab bar

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#40]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would convert over the Scribe-Android app UI to use a tab bar at the bottom of the screen. The basis of this can be seen in the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=458-1320&t=RkDNghsvxInQlM4V-1) where the application has Installation, Settings, and About tabs.

What this issue would entail is:
- An installation tab with the current home app screen
- A settings tab with any keyboard related settings
  - This does not need to be based on keyboards now!
  - Let's start with settings for all keyboards and switch to per keyboard settings at a later time
- An about tab with any contact information from the application

From here we will make more issues on expanding out the various pages of the application! 🚀

### Contribution

Happy to support as I can and review. Making this issue for @angrezichatterbox via discussions in #39 😊

**Comment by angrezichatterbox** [comment]
I would start working on this issue. :)

**Comment by andrewtavis** [comment]
Thank you, @angrezichatterbox! Really excited to see this progress :) :)

**Comment by angrezichatterbox** [comment]
<img width="426" alt="Screenshot 2024-07-15 at 10 29 31 AM" src="https://github.com/user-attachments/assets/7e3099c1-9e76-47ca-9dc4-8a385d42008f">
<img width="426" alt="Screenshot 2024-07-15 at 10 26 20 AM" src="https://github.com/user-attachments/assets/19c78a81-5d23-4bd4-a052-3d1a4717d579">

This is how the navbar looks for the dark and light modes respectively, Is there any change that you would like before I make a PR

**Comment by andrewtavis** [comment]
No stress, @angrezichatterbox! Is looking good to me 😊 We should make further issues for coloration and such, but that can be later :) Quick check on this that I'm realizing I forgot to mention: Is the tab bar able to be swiped? If so, then I think we're good to go! Would be nice to have that, but if not we could also do another issue for that :)

**Comment by angrezichatterbox** [comment]
I have added the swipeGesture for changing the tabs. I will make a PR.

**Comment by angrezichatterbox** [comment]
I have made the PR, is there any other issue you would like me to work on?

**Comment by andrewtavis** [comment]
Thanks for this, @angrezichatterbox! Give me a moment to bring the current two PRs in and then we can make some more :) Will try to review this weekend or early next week, and maybe we can do a call after?

**Comment by andrewtavis** [comment]
Closed by #41 🚀 Thank you for your dedication, @angrezichatterbox! Really amazing how quickly you've been able to figure out all of this 😊
