### ISSUE TITLE
Switch app identifier to be.scri from org.scribe

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#42]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is a simple but very important one. We now have the URL scri.be, so we should be using this in the identifiers of our applications. The Scribe-Android identifier should be switched from `org.scribe` to `be.scri` to be in line with our web presence. Maybe this change will be reflected on Scribe-iOS at some point too :)

### Contribution

Happy to review the changes here!

**Comment by andrewtavis** [comment]
Ping @angrezichatterbox 👋 Do you want to get this done, and then we can move on to others? :)

**Comment by angrezichatterbox** [comment]
Ya sure I will do it.

**Comment by andrewtavis** [comment]
Thanks, @angrezichatterbox! :)

**Comment by angrezichatterbox** [comment]
I have created a pull request solving this issue.

**Comment by andrewtavis** [comment]
Closed via #49 🚀 Thanks for this, @angrezichatterbox! Let me know if any of the new issues sound appealing. I think that once we have #48 done you could then make some issues to add individual menu elements?
