### ISSUE TITLE
Set up keyboard based settings pages

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#46]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Scribe-iOS provides settings for each individual keyboard. As seen on the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-1616&t=J8vmgQqaca9JriVj-1) as well as in the image below, each keyboard that is activated has a settings page beneath the global settings tab.

![Keyboard Settings - Light](https://github.com/user-attachments/assets/c6b05fef-fef6-47d2-8f5e-cdda7694d4f4)

This issue would do the following:

- Each installed keyboard would have an option to go to its settings on the Settings tab
- The settings page for each keyboard would just have a back button for now
- If there are no keyboards installed, then an `Install keyboards` button would be present as seen in the designs [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=653-1846&t=J8vmgQqaca9JriVj-1)
    - This is assuming that the user will not be forced to install a keyboard upon opening the app
    - We won't need to do this if we do insist that the user has already installed a keyboard to navigate through the application

### Contribution

Happy to support this any way that I can and review when we're ready to look into the solution! 😊

**Comment by andrewtavis** [comment]
Assigning this to you per our discussions, @angrezichatterbox :)

**Comment by angrezichatterbox** [comment]
Should I implement the Double space period  in the individual keyboard settings?

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋

> Should I implement the Double space period in the individual keyboard settings? 

Yes, we decided that all keyboard based settings would be in individual keyboards for consistency as some do need to be there :)

> Also, Could I make the settings page similar to Scribe-iOS? This would include making the App Language go to the App Language Settings and the current checkboxes turned into a switch similar to Scribe-iOS and Figma. Should it be kept for a separate issue? 

I think it makes sense to include it in here, yes :) All sounds great 😊 Thank you!

**Comment by angrezichatterbox** [comment]
> Yes, we decided that all keyboard based settings would be in individual keyboards for consistency as some do need to be there :)

I meant the description of the current issues states that there should be only a back button on the page for each keyboard setting. Should I implement just the double space period in the individual keyboard setting?

**Comment by andrewtavis** [comment]
Ahhhh yes yes :) I forgot for a moment that that option's already done as we don't even have it in Scribe-iOS 😇 Sounds great, thank you!

**Comment by angrezichatterbox** [comment]
I have implemented the pages and the functionality of the individual keyboard settings as the selected keyboards from the settings. 

## Keyboard Selection

| Without Keyboard Selected | With Keyboard Selected |
|---------------------------|-------------------------|
| ![Without Keyboard](https://github.com/user-attachments/assets/9e8e2a55-daac-4594-b751-f5e5f88d794a) | ![With Keyboard](https://github.com/user-attachments/assets/439094d7-8731-4598-9d79-e7c91e96b3b6) |

Are there any changes to be made or any of those switches I have implemented be moved to individual keyboard settings?

The Language settings are like below. 

<img width="300" alt="Screenshot 2024-08-21 at 7 57 21 PM" src="https://github.com/user-attachments/assets/51a862a7-6648-4fe3-806e-80c119d4cc4f">


My pr would take a little more time as for some reason  I am not able to move to app language settings even though I am using a device with API 34.

**Comment by andrewtavis** [comment]
This is absolutely beautiful, @angrezichatterbox! I think that any design changes can happen later :) Let's get this done with the work that you have left and then do another PR. Really great! 😊

**Comment by angrezichatterbox** [comment]
I have created a pull request for this issue. :)

**Comment by andrewtavis** [comment]
Closed via #63 🚀 Thanks for getting to this so quickly, @angrezichatterbox! Lots of new things that can be worked on now 😊 Will write to ask about next steps!
