### ISSUE TITLE
Plan out and implement customizable application table views

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#48]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One thing that's needed to improve the menu is that we create table views that allow for customization based on passed arguments. This issue will be a larger one, but will allow for many small issues to be made where individual menu components are added in :) Looking at the About tab from the [Figma designs](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-2206&t=aDYg9wH7ZwFKbtAN-1) as shown below:

![About Scribe - Light](https://github.com/user-attachments/assets/0e5785de-23fb-4b17-94e0-9cfb4f74808d)

We'd need customizable cells that can have a custom icon to the left, an icon to the left that's either a right chevron, an external link icon or a counterclockwise circle, and we should also consider that we need text to the left of the right icons in some instances for menu options.

### Contribution

Happy to discuss what's needed and help implement/review! 😊

**Comment by angrezichatterbox** [comment]
I implement those customizable cells where the icon is on the left and an icon on right with text in middle . Right ? .

**Comment by andrewtavis** [comment]
Yes exactly, @angrezichatterbox :) It would be great if we can easily create table view cells like the ones we already have that the needed icons. It makes sense to have a common cell with options, correct? Thank you!

**Comment by angrezichatterbox** [comment]
Ya it does make sense.

**Comment by angrezichatterbox** [comment]
<img width="377" alt="Screenshot 2024-07-31 at 4 13 31 PM" src="https://github.com/user-attachments/assets/8a9cd94b-75fb-4e04-abfc-8f0ad3893ed0">

I have tried to my the reusable component in my personal app for testing. This is what I have so far. I have created a model that takes in 3 variables. Two images and a third button image. The button could be individually added to navigate to whatever it is prescribed to do. 
Is this what had to be done or I have to do something else as well.

**Comment by angrezichatterbox** [comment]
> Ideally the entire field should be a button, @angrezichatterbox, and then the third option is an icon like the first :) Would that work?

Ya that would work and it is much easier to implement as well.

How exactly should I proceed with this in my hand. Should I implement these views in the about page? Or Should I push these implementations once its perfect for a pr.

**Comment by andrewtavis** [comment]
You can push whenever you'd like feedback, @angrezichatterbox :) Happy to take an intermediary look at it as well! As you see fit 😊

**Comment by angrezichatterbox** [comment]
<img width="377" alt="Screenshot 2024-08-02 at 6 21 44 PM" src="https://github.com/user-attachments/assets/df3da400-c166-454f-9114-7527c6441bd8">

This is what I have implemented so far . The data class could take in 2 icons a text. Along with this it we could pass it URL or activity or a function. Depending on what is passed it executes it accordingly like opening a URL navigating to a new page or executing a function. Should I consider anything else while implementing this.

**Comment by andrewtavis** [comment]
Wow this is amazing, @angrezichatterbox 🤩 Only thing would be let's make the external link icons similar to the one in the designs. I find the one in the screenshot to be a bit busy. 

Thanks so much!

**Comment by angrezichatterbox** [comment]
<img width="389" alt="Screenshot 2024-08-03 at 12 05 06 PM" src="https://github.com/user-attachments/assets/c347a376-57b6-47d1-9eda-8ac099b80ac5">
<img width="389" alt="Screenshot 2024-08-03 at 12 04 58 PM" src="https://github.com/user-attachments/assets/218c3406-f2b4-4ba9-9922-462392200150">


This is how the app looks currently in light and dark mode respectively. I have added functionality to the button according to how Scribe-iOS works. The buttons that are supposed to go to new pages will currently give a Toast message that no action is defined. Should I change any of the icons I have used in this. Any suggestion to make it better?

**Comment by andrewtavis** [comment]
No, this is perfect, @angrezichatterbox 😊 Thanks so much for all the work here! We can merge this in and then maybe you can make the issues for the needed actions? :)

**Comment by angrezichatterbox** [comment]
I have made a pull request.

**Comment by andrewtavis** [comment]
Closed via #50 🚀 Thank you, @angrezichatterbox! Really amazing to see one of the pages look so polished already! 🤩 I'll reach out about things on Matrix :)
