### ISSUE TITLE
Add Wikimedia and Scribe page to About tab

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#52]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add the `Wikimedia and Scribe` page to the About tab of the Scribe-Android application :) The designs for it can be found [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=547-1500&t=C7GHrHdRubdKpcPw-1), with an image of the page being found below:

![Wikimedia and Scribe - Light](https://github.com/user-attachments/assets/626f7715-ddae-4b55-a435-f189d7d4e789)

We'll need to include the logos for Wikidata and Wikipedia, as well as make sure that the back button for sub-pages is functioning correctly.

### Contribution

@angrezichatterbox expressed interest in working on this one 😊 Happy to review and support as I can!

**Comment by angrezichatterbox** [comment]
So currently there is an action bar at the top for the Scribe-Android. Would it be removed at some point to make the app similar to Scribe-iOS?If so should I consider that and make the Wikimedia and Scribe Text not on the action bar or should I put it on the action bar for now?

**Comment by andrewtavis** [comment]
Maybe it's ok to leave it, @angrezichatterbox? We have a top header for Scribe-iOS as well that will function similar to an action bar. That also has a light shadow under it on scroll, so I think if we just blend the action bar in it's basically the same?

**Comment by angrezichatterbox** [comment]
I have created a pull request for this. I haven't customized the action bar for the page since it would be better if that were done universally for all pages together. Please do give suggestions for any changes to be made to the page. :)

**Comment by andrewtavis** [comment]
Closed via #54 🎉 So much progress, @angrezichatterbox! Really is starting to take shape, and it was super great to be able to tell the Wikidata Lexeme community that there's been so much progress here! Thanks so much :)
