### ISSUE TITLE
Remove settings cog from Scribe keyboards

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#55]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Now that #15 has been closed, we no longer need the settings cog at the top of the Scribe keyboard as this was meant to be used to change the keyboard in the original application that Scribe-Android was forked from. See the screenshot below for where the cog is:

![Screenshot_20240811_134118](https://github.com/user-attachments/assets/e3d4b01c-53d5-47fa-943d-a86ec39caa61)

This issue would remove it and make the Command Bar span the rest of the screen over where the cog currently is.

### Contribution

Happy to review and assist as needed! This is a `good first issue` for someone who wants to get into Scribe-Android development! 🤖

**Comment by Linfye** [comment]
Can I work on this?

**Comment by andrewtavis** [comment]
Would be great, @Linfye! Let us know if we can support somehow. Remember that we also want to extend out the command bar, not just remove the settings cog :)

**Comment by andrewtavis** [comment]
Closed by #78 😊 Looking forward to the next issue, @Linfye! We'll be making a few more in the coming days :)
