### ISSUE TITLE
Addition of Legal Tab to About Page

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#58]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the About page in Scribe-Android features two tabs: Community and Feedback & Support. To improve the app and align it with Scribe-iOS we would need to add a "Legal" tab to the About page.

Below are the current About Pages with 2 tab views. 
<img width="366" alt="Screenshot 2024-08-16 at 3 07 36 PM" src="https://github.com/user-attachments/assets/58a10aa5-58da-402a-9231-5d35fad08ec9">

The required changes would be to add the legal tab and the tab should include the Privacy Policy and Third party license section as seen below. 

![IMG_6637](https://github.com/user-attachments/assets/a2242cdb-88dc-4ffa-9f5d-884e3aeb3f54)

### Contribution

I will be working on this.

**Comment by andrewtavis** [comment]
Thanks for the issue here, @angrezichatterbox! All looks great to me 😊 I added it to the board and categorized it, and also assigned you. You can feel free to do these as well and we can discuss if you got the priorities and the focus right for the board! I'm sure those will be fine when you do them, and it doesn't have to be perfect :)

**Comment by angrezichatterbox** [comment]
I have made a pull request for this issue. :)

**Comment by andrewtavis** [comment]
Closed by #61 🎉 I'll remove the blocks on the other issues now, @angrezichatterbox :) :)
