### ISSUE TITLE
Add the Privacy policy page to About tab

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#59]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add the Privacy Policy page to the About tab of the Scribe-Android application. The image of the page is given below and the designs can be checked out [here on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=547-1500&t=C7GHrHdRubdKpcPw-1). 

<img src="https://github.com/user-attachments/assets/5c330651-0bac-45d0-9ef2-aa7ca1cb76b2" alt="Privacy Policy - Light" width="350"/>

- Note: The issue is currently blocked #58 where we would be adding the legal tab view to the about page where there would be a section to navigate to the privacy policy and third-party license page. 

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by Linfye** [comment]
I can work on this. Could you tell me more details about this?

**Comment by angrezichatterbox** [comment]
Thank you very much!

The current About Page includes a Legal Tab with two options. This issue involves adding navigation from the Privacy Policy option to a new activity. The layout for this new activity is detailed in the issue description.

To address this issue, you need to:

- Create the new activity layout as specified in the issue description.
- Implement navigation so that selecting the Privacy Policy option in the Legal Tab takes the user to the new activity.
- You can achieve this by adding the new activity to the RecyclerView data in the About Activity.

A reference for a similar layout can be seen on the Wikimedia Scribe Page. 

Feel free to ask any queries :)

**Comment by andrewtavis** [comment]
Realized that I forgot to assign, @Linfye :) Please let us know if you have any questions here!

**Comment by andrewtavis** [comment]
Closed via #72 🚀 Thanks so much for the work of getting up to speed with Scribe-Android, @Linfye! Amazing to have your contributions here as well :)
