### ISSUE TITLE
Add the Third party license page to the About tab

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#60]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add the Third Party License page to the About tab of the Scribe-Android application. The image of the page is given below and the designs can be checked out [here on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=547-1500&t=C7GHrHdRubdKpcPw-1). 

 <img src="https://github.com/user-attachments/assets/9b8a3931-540a-4028-ae0f-035d08f50ef4" alt="Third-party-License" width="350"/>

Since the reference of this keyboard is simple keyboard the content has to be slighly modified to include [Simple keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard)

- Note: The issue is currently blocked #58 where we would be adding the legal tab view to the About page where there would be a section to navigate to the privacy policy and third-party license page. 

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by Linfye** [comment]
This issue appears to be similar to #59. I think I can do this. :)

**Comment by angrezichatterbox** [comment]
Feel free to work on the issue :). If you have any questions, feel free to ask us here.

**Comment by andrewtavis** [comment]
Thanks for picking this up, @Linfye!

**Comment by andrewtavis** [comment]
Closed by #75 :) Thanks for getting to all of this so quickly, @Linfye! 🚀
