### ISSUE TITLE
Menu item to disable accent characters on keyboard letter keys

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#65]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The issue is to create a menu item for enabling and disabling accent characters. 

Examples would include:

- German would disable `ä`, `ö` and `ü`
- Spanish would disable `ñ`
- Swedish would disable `ä`,`ö`and `å`
- ...

A corresponding issue would be created to implement the functionality of the enabling accent characters. The menu item should be present in the individual keyboard settings as seen in the [Figma Design](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=614-1889&t=URM6JbDzC17q9xG1-4).  The default of this option would be that it's selected. Deselecting this option would then add these to the alternate characters for the given keyboard.  For now on change a Toast Message could be displayed.

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by angrezichatterbox** [comment]
I will work on this and #67

**Comment by andrewtavis** [comment]
I think both in the same PR would make sense as long as it works for you, @angrezichatterbox :)

**Comment by andrewtavis** [comment]
Thanks for getting to both of these in one PR, @angrezichatterbox! Made the review very seamless 😊
