### ISSUE TITLE
Add emoji autocompletions

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#66]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The issue is to implement emoji suggestions based on the text we would type using the keyboard. 

- The issue is currently being blocked by #64 where we would be adding a menu option to enable and disable emoji suggestions and #138 where the buttons are added

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by Linfye** [comment]
Is this issue ready? Can I start working on it now? 😊

**Comment by andrewtavis** [comment]
We'd need #89 to get finished before we work on this one, @Linfye :) Do you want to pick up one of the refactoring issues, and hopefully @angrezichatterbox can finish up #89 in the coming days?

**Comment by andrewtavis** [comment]
Assigning you to work on it when it's unblocked though :)

**Comment by Linfye** [comment]
OK, I'll work on other issues now. 😊

**Comment by angrezichatterbox** [comment]
> We'd need #89 to get finished before we work on this one, @Linfye :) Do you want to pick up one of the refactoring issues, and hopefully @angrezichatterbox can finish up #89 in the coming days?

Yes I will try my level best to complete it in the coming days.

**Comment by andrewtavis** [comment]
As you have time for it, @angrezichatterbox :)

**Comment by andrewtavis** [comment]
Hey @Linfye 👋 I just added in #138 to add in the buttons for emoji autosuggestions, which in hindsight is also blocking this (updated the issue text to reflect this). Would you have interest in adding these buttons to the keyboard interface?

**Comment by Linfye** [comment]
I'd like to do this. I will start it after finishing #113. 😄

**Comment by andrewtavis** [comment]
Nice @Linfye! Feel free to write in there and I'll assign :)

**Comment by Linfye** [comment]
Is this issue ready now? @andrewtavis 😊

**Comment by andrewtavis** [comment]
I'd say so, yes @Linfye :) Maybe we'll need a minor edit post data update, but I actually don't think that the emoji data will change much. Unblocking 🎉

**Comment by andrewtavis** [comment]
Closed by #220 :) Thanks for the patience and determination here, @Linfye!
