### ISSUE TITLE
Disable keyboard accent characters for certain languages. 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#67]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The issue would disable keyboard accent characters for certain keyboards. 

 Examples would include:

- German would disable ä, ö and ü
- Spanish would disable ñ
- Swedish would disable ä, ö and å
- ...

This issue is currently being blocked by #65 where we would implement the menu options to disable accent characters. 

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by andrewtavis** [comment]
Closed by #172 :) Thanks @angrezichatterbox! Keyboard options are really coming along 😊
