### ISSUE TITLE
Migrate from Kotlin synthetics to Jetpack view binding

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#68]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The `Kotlin-android-extensions` Gradle plugin is deprecated. To ensure future compatibility and to take advantage of the latest features, we need to migrate our app from using Kotlin Android Extensions to use ViewBinding. 

### Contribution

I’m happy to take on this issue and am more than willing to assist anyone else who wants to work on it. 😄

**Comment by angrezichatterbox** [comment]
Yes, I would work on this. It wouldn't take too long as well.

**Comment by angrezichatterbox** [comment]
I have created a pull request for this issue.

**Comment by andrewtavis** [comment]
Thanks for the quick fix here, @angrezichatterbox! Really nice to have the build settings up to date and everything working so nicely 😊
