### ISSUE TITLE
Kotlin linting workflow

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#70]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a `.github/workflows/pr_kotlinlint` or another similarly named file to the repo with the intent of checking the Kotlin code for the project on each pull request. We'll need to look for a valid GitHub Action to check the code, with this then being set up in a similar way to [Scribe-iOS' pr_swiftlint.yaml](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/workflows/pr_swiftlint.yaml). We'll maybe need to ignore some rules at first, and then we can slowly fix any syntax/formatting suggestions as work is done 😊

### Contribution

Happy to support or get to this eventually myself! This is a `good first issue` for someone who wants to get into Scribe-Android development a bit! :)

**Comment by ItsAbhinavM** [comment]
I have made a PR for this issue.

**Comment by andrewtavis** [comment]
Changes made in #79 have finished this up now :) :) We now have ktlint and detekt workflows running on PRs. @angrezichatterbox, let me know if any help is needed making the issues to enable the linting errors we skipped and fix the errors!

Thanks also for the initial work here, @ItsAbhinavM! 😊

**Comment by angrezichatterbox** [comment]
> Changes made in #79 have finished this up now :) :) We now have ktlint and detekt workflows running on PRs. @angrezichatterbox, let me know if any help is needed making the issues to enable the linting errors we skipped and fix the errors!
> 
> Thanks also for the initial work here, @ItsAbhinavM! 😊

I will create individual issues for those 4 that we have disabled. :)

**Comment by andrewtavis** [comment]
Thank you, @angrezichatterbox!
