### ISSUE TITLE
Add back button to app menu sub pages

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#76]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One thing that's needed for Scribe-Android is back buttons for when a user navigates to a sub pages within the app's menu. The back button can be seen in the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=547-1500&t=CFEipBvDSeXA8rp2-1) at the top left of each page that in a sub page of the main installation, settings and about pages.

### Contribution

Happy to review this and get to it eventually if need be! 😊

**Comment by andrewtavis** [comment]
@angrezichatterbox, would this one make sense for you as it's a bit more low level for how the menu functions?

**Comment by andrewtavis** [comment]
I guess a custom action bar such that we can include the formatting of the top of it to make the color the same as the app background color in dark mode and also have it be that there's no line/shadow between the action bar and the app background? If that sounds good to you :?

**Comment by angrezichatterbox** [comment]
> Generally matching Scribe-iOS as much as possible would be good, but if you then that there are benefits to changes then let me know and we can talk them though 😊 Happy to have things over here also go over to iOS if we think they're improvements! I think the way the bottom tab bar icon for the current page gets a bit bigger is actually pretty nice and maybe something we want for iOS. As of now it's just the same size. What do you think? You could make an issue in iOS for it? :)


Yes, the material navigation bar highlights the current tab by either bolding the text or increasing its size. I too feel this feature would be a good addition to Scribe-iOS, as it provides a clearer indication of the selected tab compared to just a color change. I can create an issue for this in Scribe-iOS. :).

**Comment by angrezichatterbox** [comment]
I have created a pull request for this issue. I have tried to make it similar to Scribe-iOS. If there are any changes to be made I will be happy to do it :).

**Comment by andrewtavis** [comment]
Closed by #77 🚀 We're getting really close with the menu, @angrezichatterbox! Crazy all of the progress we've been making over the last few months. Thanks so much!
