### ISSUE TITLE
Migrate the build configuration from Groovy to Kotlin 

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#80]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Android Gradle plugin 4.0 added support for using Kotlin in your Gradle build configuration to replace Groovy, the programming language traditionally used in Gradle configuration files.

Currently, the app uses Groovy for the Build configuration at the project and app levels. This issue is to convert it to Kotlin-based Build configuration with extensions .gradle.kts. 

This helps us to follow the current standard in Android Development and helps new contributors to easily add plugins as new documentation for plugins have additions to .gradle.kts files listed more directly as it is the new standard. 

The migration guide is given below 
[Migration Guide](https://developer.android.com/build/migrate-to-kotlin-dsl)

### Contribution

I am happy to work on this issue and more than willing to help anyone who is interested to work on this issue :).

**Comment by andrewtavis** [comment]
Might make sense for you to work on this one, @angrezichatterbox :) We can leave it for a moment in case someone wants to pick it up, but I'd say it's important for this to be done before Hacktoberfest so we're not trying to merge this in at the same time as other PRs 😊

**Comment by angrezichatterbox** [comment]
> Might make sense for you to work on this one, @angrezichatterbox :) We can leave it for a moment in case someone wants to pick it up, but I'd say it's important for this to be done before Hacktoberfest so we're not trying to merge this in at the same time as other PRs 😊

I will work on this issue for now. If anyone picks  it up soon let them continue working on this issue.

**Comment by andrewtavis** [comment]
Closed by #82 🚀 Maybe would be best to focus on making all of the ktlint and detekt issues now, @angrezichatterbox :) Just so we don't forget. But also a task for tomorrow as it's quite late for you now!

**Comment by angrezichatterbox** [comment]
> Closed by #82 🚀 Maybe would be best to focus on making all of the ktlint and detekt issues now, @angrezichatterbox :) Just so we don't forget. But also a task for tomorrow as it's quite late for you now!

I have made the issues for the ktlint one. detekt I will be making tmrw Thanks :)
