### ISSUE TITLE
Descriptions for setting items

### ISSUE THREAD

**Issue by Linfye** [scribe-org/Scribe-Android#83]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

I noticed that there is a short description below each setting items in [Figma Design](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=614-1889&node-type=FRAME&t=aAiABFmlfV4dzCeB-0)(like Double space periods and Autosuggest emojis). And there's no such part in the current APP. I think we can add this for now and future reference.

### Contribution

I'd like to work on this. 😊

**Comment by andrewtavis** [comment]
Would be great to get your help here, @Linfye! Assigning now, and please let us know if you need some support :) 

CC @angrezichatterbox 😊

**Comment by andrewtavis** [comment]
Closed by #94 🎉 Really appreciate you making this issue, @Linfye! Please feel free to make others that you think are necessary and we'll discuss and implement from there :)
