### ISSUE TITLE
Fix Property Naming Linting Issues Identified by Ktlint

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#84]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Ktlint has identified linting issues related to property naming conventions in the application. These issues need to be resolved by correcting the property and constant naming according to the expected conventions.

Ktlint expects the following naming conventions:

Properties: `Should be in camelCase.`
Constants: `Should be in UPPER_SNAKE_CASE.`

More about this could be understood from [Ktlint Docs](https://pinterest.github.io/ktlint/1.0.0/rules/standard/#property-naming)

The Files to be modified to fix these linting issues can be found out by:

- Comment or remove the `ktlint_standard_property-naming = disabled` from the .editorconfig file 
- Run the command ./gradlew lintKotlin in your terminal 
- You would get the list of files which the linting issues caused by property naming errors. 

### Contribution

I would love to work on this and am more than willing to help anyone interested in taking on this issue. :)

**Comment by Linfye** [comment]
When I attempt to fix this part of these ktlint errors, I'm unclear on how to proceed.
```
private val GENERIC_PERM_HANDLER = 100
private val DELETE_FILE_SDK_30_HANDLER = 300
private val RECOVERABLE_SECURITY_HANDLER = 301
private val UPDATE_FILE_SDK_30_HANDLER = 302
```
According to the current variable naming, these are constants and should be in uppercase. However, ktlint recommends using camel case for property names. Should I extract these variables and declare them as constants in uppercase, or should I rename them all to camel case?

**Comment by angrezichatterbox** [comment]
> When I attempt to fix this part of these ktlint errors, I'm unclear on how to proceed.
> 
> ```
> private val GENERIC_PERM_HANDLER = 100
> private val DELETE_FILE_SDK_30_HANDLER = 300
> private val RECOVERABLE_SECURITY_HANDLER = 301
> private val UPDATE_FILE_SDK_30_HANDLER = 302
> ```
> 
> According to the current variable naming, these are constants and should be in uppercase. However, ktlint recommends using camel case for property names. Should I extract these variables and declare them as constants in uppercase, or should I rename them all to camel case?

You could try keeping them in the companion object.
