### ISSUE TITLE
Fix Linting Issues Related to Wildcard Imports

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#85]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Ktlint has identified issues related to wildcard imports in the application. These issues need to be resolved by updating the import statements to avoid using wildcard imports.

**Ktlint Expected Import Conventions:**

- **Wildcard Imports:** Wildcard imports should be avoided. Instead, use explicit imports for each class or function to improve code clarity and maintainability.

**Example:**

```kotlin
// Incorrect: Avoid using wildcard imports
import java.util.*

// Correct: Use explicit imports
import java.util.Scanner
import java.util.List
```

For more details, refer to the [Ktlint Documentation on Wildcard Imports](https://pinterest.github.io/ktlint/1.0.0/rules/standard/#no-wildcard-imports).

**Steps to Identify and Resolve Issues:**
 - Ensure that wildcard import rules are enabled by commenting out or removing the line `ktlint_standard_no-wildcard-imports = disabled` in your `.editorconfig` file.
 - Execute `./gradlew lintKotlin` in your terminal. This will generate a list of files containing wildcard import issues.
- Review the output from the linting check to identify files with wildcard imports.
- Update the import statements in these files to use explicit imports instead of wildcards.

### Contribution

I would love to work on this and am more than willing to help anyone interested in taking on this issue. :)

**Comment by andrewtavis** [comment]
Closed by #102 🚀 Thanks for picking this up, @Linfye! 🎉
