### ISSUE TITLE
Fix Backing Property Naming Issues

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#86]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Ktlint's backing property naming rule has been disabled (ktlint_standard_backing-property-naming = disabled). This rule should be enabled and applied to ensure proper naming conventions for backing properties.

Ktlint Expected Backing Property Naming Conventions:

Backing Properties: Should follow the prescribed naming conventions, typically using a prefix or suffix to clearly indicate their role as backing properties.

```
// Incorrect: Naming does not follow the convention
private val _data = mutableListOf<String>()

// Correct: Follow naming convention for backing properties
private val _dataList = mutableListOf<String>()

```

Refer this [docs](https://pinterest.github.io/ktlint/1.0.0/rules/standard/#no-wildcard-imports) for more info 

#### Steps to fix the issue

- Comment out or remove the line ktlint_standard_backing-property-naming = disabled from your .editorconfig file to re-enable this rule.

- Execute ./gradlew lintKotlin in your terminal to identify files with backing property naming issues.

- Update the names of backing properties in these files to follow the Ktlint naming conventions.

### Contribution

I would love to work on this and am more than willing to help anyone solve this issue. :)

**Comment by andrewtavis** [comment]
Closed by #103 🙌 Thank you for getting to all these great lint fix contributions, @Linfye!
