### ISSUE TITLE
 Fix Filename Convention Issues

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#88]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Ktlint's filename convention rule has been disabled (ktlint_standard_filename = disabled). This rule should be enabled and applied to ensure that filenames follow the correct naming conventions.

The file naming should follow the  `PascalCase` 

```
// Incorrect: Filename does not follow convention
user_profile.kt

// Correct: Filename follows the convention
UserProfile.kt
```

For more information this [docs](https://pinterest.github.io/ktlint/1.0.0/rules/standard/#file-name) could be refrerred

- Comment out or remove the line `ktlint_standard_filename = disabled` from your .editorconfig file to re-enable this rule.
- Execute ./gradlew lintKotlin in your terminal to identify files with filename convention issues.
- Rename the files to comply with the Ktlint filename conventions.

### Contribution

I would love to work on this issue and am more than willing to help anyone interested to work on this issue. :)

**Comment by andrewtavis** [comment]
Closed by #104 :) :) Thanks so much, @Linfye!
