### ISSUE TITLE
Create basic UI of command key functionality

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#89]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a quite important issue for Scribe-Android and the first major step towards Scribe functionality on the keyboard. This issue will add buttons for the commands above the keyboard, which further will be used for autosuggestions and other functions.

Specifically we need:
- To the immediate right of the Scribe key a button for translation, followed by conjugation, followed by plural
    - See the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=0-711&t=KUyTw4U8e3YLt11R-1) with images that include the buttons as autosuggestions
- In the base key view these buttons should be clear and just have labels
    - The labels for now can be `Translate`, `Conjugate` and `Plural` respectively
- We need to then have the following states from Scribe-iOS added - see [Keyboards/KeyboardsBase/InterfaceVariables.swift#L108](https://github.com/scribe-org/Scribe-iOS/blob/e3ed1de13585ac74f486d48cfad72c9a2a0b9675/Keyboards/KeyboardsBase/InterfaceVariables.swift#L108)
    - The buttons should be clear for `idle`
    - When the Scribe key is pressed, the state should change to `selectCommand` and the buttons should turn Scribe blue
    - When any of the command buttons are selected when the state is `selectCommand`, the state should change to their corresponding one - i.e. press `Translate` while the state is `selectCommand` should change the state to `translate`
    - When the state is `translate`, `conjugate` or `plural`, the command bar should be displayed as it is now

We can do any further functionality from here. Still lots to do on commands, but we can start from here!

### Contribution

Happy to review and answer any questions or provide any guidance! 😊

**Comment by andrewtavis** [comment]
@angrezichatterbox, this would also be one I'd think would be good for you so that you can set up the basis for the commands, and from there we can work on some other minor functionality parts :) :)

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, this would also be one I'd think would be good for you so that you can set up the basis for the commands, and from there we can work on some other minor functionality parts :) :)

Yes. I will be working on this issue.

**Comment by andrewtavis** [comment]
Nice, great @angrezichatterbox :) Let me know if you have any questions!

**Comment by andrewtavis** [comment]
Closed by #101 🚀 Really amazing to see the keyboard take this first great step, @angrezichatterbox!
