### ISSUE TITLE
Linting issues due to line length

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#93]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Methods or lines of code that exceed the maximum allowed line length can be hard to read and maintain. To improve readability and maintainability, it is essential to ensure that lines do not exceed the maximum line length specified in the coding standards.

Before fixing:

```
fun someLongMethodName(param1: String, param2: Int, param3: Boolean): String {
    // This is an example of a method with lines exceeding the maximum length
    val longString = "This is an example of a very long string that exceeds the maximum allowed line length and should be refactored to be more readable and maintainable."
}

```

After fixing:

```
fun someLongMethodName(param1: String, param2: Int, param3: Boolean): String {
    // Refactored method with lines within the maximum length
    val longString = "This is an example of a very long string that " +
                     "is now split into multiple lines to adhere " +
                     "to the maximum allowed line length and improve readability."
}

```

More about this can be understood from the [docs](https://detekt.dev/docs/rules/formatting/#maximumlinelength)

The lines to fix can be found out by:
- Enable the MaxLineLength rule in your detekt.yml
- Run the command ./gradlew detekt in the termianal
- You would be able to see the lines where the errors occurs 

### Contribution

I would love to work on this and more than willing to help anyone solve this issue. :hap

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis and @angrezichatterbox can I be assigned this issue?

**Comment by angrezichatterbox** [comment]
> Hi @andrewtavis and @angrezichatterbox can I be assigned this issue?

Assigned :)  Thanks for taking up the issue.

**Comment by andrewtavis** [comment]
Closing as this was finished in #213 :)
