### ISSUE TITLE
Convert all strings to Scribe-i18n keys

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#95]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in #94, changes in [Scribe-i18n](https://github.com/scribe-org/Scribe-i18n) that just went through mean that we now have all the strings from the designs within the language i18n files. It would be great if we could update the Scribe-i18n subtree and then convert all strings in the application over to Scribe-i18n keys.

### Contribution

Happy to review and support as needed!

**Comment by andrewtavis** [comment]
@angrezichatterbox, I'm also thinking that this one might make sense for you as this would allow you to check that I've added all of the strings you mapped out? Thoughts on picking this up? :)

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, I'm also thinking that this one might make sense for you as this would allow you to check that I've added all of the strings you mapped out? Thoughts on picking this up? :)

Yes I'll work on this once #89 is done.

**Comment by andrewtavis** [comment]
Thanks, @angrezichatterbox! We'll be in a great place once this and #89 are done :) :)

**Comment by angrezichatterbox** [comment]
Should I run the scripts for the conversion of the i18n strings to XML now or should it be done in the i18n and then pushed there as the current XML isn't updated according to the updated jsons.

**Comment by andrewtavis** [comment]
I think it's fine for you to run the scripts and send along a PR. I'll merge tonight and then work can begin on this tomorrow :)

**Comment by andrewtavis** [comment]
https://github.com/scribe-org/Scribe-i18n/commit/5701774cc4f4cd7665d86eb264a176c9627b95d9 just sent along the changes you suggested for Scribe-i18n, @angrezichatterbox :) Maybe we can close this issue via another minor edit to convert the last missing strings?

**Comment by andrewtavis** [comment]
Closed by #105 and #106 🚀 Thanks so much for this, @angrezichatterbox! Really awesome to be building so sustainably from the start 😊
