### ISSUE TITLE
Fix linting issues due to variable naming detected by detekt

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#97]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

There are certain rules to be followed while naming variables as per convention followed by detekt. These can be understood from 
(docs)[https://detekt.dev/docs/rules/naming/]

The issue aims to fix all the linting issues for this reason. The specific lines to fix can be found by the following steps.

Steps for finding the lines of error:
- Remove or comment off or turn it to turn for the following line from the detekt.yml
```
naming:
    VariableNaming:
        active: false
```
- Run the command `./gradlew detekt`
- You would be able to see which line to fix.

### Contribution

I would love to work on this issue and am more than willing to help anyone solve this issue. :)

**Comment by andrewtavis** [comment]
Closed by #175 :) Thanks much, @DeKaN!
