### ISSUE TITLE
Fix linting issues due to unused variable or properties as found by detekt

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#98]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Certain variables are initialized but never used in the codebase. The issue aims to remove those variables from the codebase. 

Such variables can be found by the following steps:

- Remove or comment off the following line or turn it to true

```
    UnusedPrivateProperty:
        active: false
```
- Run the command `./gradlew detekt` in your terminal
- You would be able to see all the lines where there are unused variables in a specific file. 

### Contribution

I would love to work on this and am more than willing to help anyone fix the issue.

**Comment by Yashvardhan-17** [comment]
Hi, I would like to work on this.

**Comment by angrezichatterbox** [comment]
> Hi, I would like to work on this.

Yes Feel free to work on this issue. In case of any queries ask it here :) .

**Comment by andrewtavis** [comment]
Thanks for your interest in helping, @Yashvardhan-17!

**Comment by andrewtavis** [comment]
10th contributor! Thanks so much for the contribution, @Yashvardhan-17 😊
