### ISSUE TITLE
Fix linting issues caused by functions parameters not being used by the function

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#99]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Some functions have parameters not being used by the function. The issue aims to remove those unused parameters. 

Steps to see which all lines have to be modified:
- Comment or remove or make it to true for the following line in detekt.yml
```
   UnusedParameter:
        active: false
```
- Run the command `./gradlew detekt`
- You would be able to see which all files have to be modifed. 

### Contribution

I would love to work on this and am more than willing to help anyone to solve this issue.

**Comment by Yashvardhan-17** [comment]
Hi, I would like to work on this issue.

**Comment by angrezichatterbox** [comment]
> Hi, I would like to work on this issue.

Yes feel free to work on this issue. In case of any queries do ask here. Thank you :)

**Comment by Yashvardhan-17** [comment]
Hey @angrezichatterbox, after removing the unused parameters, we'll encounter an argument mismatch error. Would you like me to update those function calls to fix the issue?.

**Comment by angrezichatterbox** [comment]
> Hey @angrezichatterbox, after removing the unused parameters, we'll encounter an argument mismatch error. Would you like me to update those function calls to fix the issue?.

Yes, You can go ahead and update the function calls to  remove the unused variables.

**Comment by andrewtavis** [comment]
Closed by #146 :) Hope to work with you again soon, @Yashvardhan-17! 🚀
